### ISSUE TITLE
Open VPN doesnt change the computer IP

### ISSUE THREAD

**Issue by fravia1** [toulousain79/MySB#10]
Hi,

Thanks for your script again .

I was testing the open VPN  settings TAP and TUN both but with the current settings its logs in well with openvpn but the ip of the computer doesn't change .

Regards

**Comment by toulousain79** [comment]
Hi,
TAP "mode" is not finished. I want to use it for DLNA. With it you can not redirect your traffic.
TUN without gateway works fine.

For TUN with redirect traffic, I found the error.
Run these commands

--> MySB_GitHubRepoUpdate
AND
--> MySB_SecurityRules create

If you use a MS Windows machine, think to start the OpenVPN GUI with administrator privileges.

The next site allows you to check that you surf with server IP and also verifiy that you are using DNScryp-proxy DNS.
https://dnsleaktest.com/

You can also check if DNSsec is enabled with next address.
https://dnssectest.sidnlabs.nl/index.php

Please, tell me if it's ok for you now.

Thanks a lot for you help.
