### ISSUE TITLE
systemctl reload cron

### ISSUE THREAD

**Issue by MetalDevOps** [toulousain79/MySB#102]
## Simple description of the problem

Was receiving an error email "Failed to reload cron.service: Job type reload is not applicable for unit cron.service." I think the reason is using the systemctl reload cron command in the file MySB/install/Cron

can be used "sudo service cron reload" or "/etc/init.d/cron reload" instead

## Reproduce

Steps to reproduce the problem:

1. type systemctl -p CanReload show cron.service, here the output is CanReload=no
2. type systemctl reload cron, here the output is Failed to reload cron.service: Job type reload is not applicable for unit cron.service.
3.  type "sudo service cron reload" here the output is "[ ok ] Reloading configuration files for periodic command scheduler: cron." works.

## Screenshot

![](https://i.imgur.com/b3IglAI.png)

## Hardware and environment

- Provider: Online.net
- Server type: Dedi
- MySB version: 7.0
- Kernel version: Linux server6.kyo.ninja 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
- Hardware: Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz, 4 cores, 32GB ram, 2x4TB Raid 0

**Comment by toulousain79** [comment]
Hi,

Thanks for your feedback !
Thanks to you I have been able to fix the same problem for DNScrypt-proxy.

You can run the `MySB_GitHubRepoUpdate` command or wait for 12:00 tomorrow.
