### ISSUE TITLE
[BUG] Bad response from server: (200 [parsererror,getplugins]) SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by MetalDevOps** [toulousain79/MySB#103]
## Simple description of the problem

I just installed Debian and right after MySB and when opening rutorrent gives this error.

## Reproduce

Just install debian and install MySB

## Screenshot

![](https://i.imgur.com/SnTl8Mk.png)

## Logs

No installation errors in the logs, everything was installed correctly.

## Hardware and environment

Provider: Online.net
Server type: Dedi
MySB version: 7.0
Kernel version: Linux server6.kyo.ninja 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
Hardware: Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz, 4 cores, 32GB ram, 2x4TB Raid 0

**Comment by toulousain79** [comment]
Hi

You can do this
service dnscrypt-proxy restart

And do a CTRL+F5 or CTRL+R in your browser.

**Comment by JustShinobi** [comment]
It didn't work, I had tried to disable dnscrypt-proxy completely before, actually tried everything that came to mind.

**Comment by toulousain79** [comment]
Please, Can you check /var/log/nginx/rutorrent.log ?
And check with F12 in you browser to check any internet access error ?

**Comment by JustShinobi** [comment]
Here the logs:

[rutorrent-access.log](https://github.com/toulousain79/MySB/files/3724397/rutorrent-access.log)
[rutorrent-error.log](https://github.com/toulousain79/MySB/files/3724398/rutorrent-error.log)

any internet error.

note: obviously i changed my IP and my server address for "myipaddress" and "myserveraddress:8189" respectively.

**Comment by toulousain79** [comment]
Removed of sync and for_rsync plugins.
Do a `MySB_GitHubRepoUpdate`

**Comment by JustShinobi** [comment]
[rutorrent-error.log](https://github.com/toulousain79/MySB/files/3725759/rutorrent-error.log)
[rutorrent-access.log](https://github.com/toulousain79/MySB/files/3725760/rutorrent-access.log)

I did a new install of debian and installed MySB, the problem continues, I tried service dnscrypt-proxy restart and it did not solve.

**Comment by toulousain79** [comment]
Please, come to Discord https://github.com/toulousain79/MySB/wiki/%5BHelp%5D-Support
Did you have Anydesk ?
I will try a new installation to check that

**Comment by JustShinobi** [comment]
i am KyO.NinjA on discord.

**Comment by JustShinobi** [comment]
reinstalling debian again, will try again with fresh install.

**Comment by toulousain79** [comment]
the faulty plugin is fileupload...
Please do a `MySB_GitHubRepoUpdate` and add a feedback

**Comment by Merlincool** [comment]
> the faulty plugin is fileupload...
> Please do a `MySB_GitHubRepoUpdate` and add a feedback

Yes I am stuck after enabling fileupload plugin, I checked this Solution https://github.com/toulousain79/MySB/commit/8c9f960f5ae0e4d57b0bc66959192838686ae2ff but I am totally not understanding what I am suppose to do? can you give some brief.
