### ISSUE TITLE
Use rtorrent 0.13.6/0.9.6

### ISSUE THREAD

**Issue by Lucif3r-MorningSter** [toulousain79/MySB#106]
many trackers does not work well with the latest 0.13.7 and 0.13.8. Please add an option to use the 0.13.6 version.

**Comment by toulousain79** [comment]
nope, no adding v0.13.6 in sight for now ...
describe me your problem with some of these trackers, and please, give me the name of these trackers in private message on Discord
have you updated to MySB v7.1?

[MySB - Options Systèmes](https://mysb.gitbook.io/doc/configuration/options-systemes)
[MySB - Les trackers](https://mysb.gitbook.io/doc/mysb-en-detail/les-trackers)

**Comment by toulousain79** [comment]
hi
you do not want to explain to me what kind of problems you encounter with versions 0.9.7 and 0.9.8?
I close this issue...
