### ISSUE TITLE
Dysfonctionnement que la synchro automatique après téléchargement d'un torrent

### ISSUE THREAD

**Issue by eyden23** [toulousain79/MySB#107]
Un torrent ajouté dans une catégorie ne se synchronise pas tout seul une fois terminé
par contre avec "Remettre un téléchargement dans la liste d'attente", pas de soucis.

le mode de synchro est bien en "Synchronisation directe"
j'utilise le script par défaut
Le script en lui meme fonctionne bien quand je le lance via "Remettre un téléchargement dans la liste d'attente"
je suis allé jusqu'à tout retirer (les catégories) et redemarrer la sdbx, rien à faire

**Comment by toulousain79** [comment]
Hello
Je viens de faire un essaie avec la 7.1 et je peux confirmer la synchro directe fonctionne parfaitement...

**Comment by toulousain79** [comment]
Hello,

Effectivement, j'ai trouvé une petite régression dans le script de synchro par défaut...
Bug rencontré lors de l'ajout via ruTorrent ou plugin _(ex: Xirvik)_.

Le patch a déjà du être appliqué sur ta machine à 12h.
Mais tu peux aussi forcer l'application manuellement via les commandes suivantes:

```
MySB_GitHubRepoUpdate
MySB_UpdateTools
MySB_SecurityRules create
```

Tiens moi au just stp
