### ISSUE TITLE
Question par rapport a ton script ?

### ISSUE THREAD

**Issue by romainlavisse** [toulousain79/MySB#109]
Salut,
je viens de trouver ton script et il a l'air ultra complet.
J'ai deux questions : 

- L'installation comprend t-elle le plugin autodl-irssi ?
- Peut on continuer d'utiliser le serveur normalement apres ? (apt-get et autre commande normale sur linux) car tu parles de la commande MySB_UpgradeMe pour faire des MAJ

Merci

**Comment by toulousain79** [comment]
Salut,
Je pense t'avoir répondu mais n'en suis pas certain.

Le plugin autodl-irrsi n'est pas inclus.
Tu peux continuer d'utiliser le serveur normalement, mais tu peux prendre le risque que les màj de MySB se fassent mal, ou ajouter un gravier dans le rouage.

La commande `MySB_UpgradeMe` ne sert uniquement qu'à mettre à jour MySB.
Par contre, la commande `MySB_UpgradeSystem`, permet quant à elle, de mettre à jour Debian.

[Les commandes MySB](https://mysb.gitbook.io/doc/mysb-en-detail/binaires-and-scripts#les-commandes-mysb)
