### ISSUE TITLE
Installation qui plante debian 10

### ISSUE THREAD

**Issue by shaine93** [toulousain79/MySB#119]
Bonsoir sur une fresh installation sur debian 10  sur Hetzner , il bug sur l'install de sendbox manager , les points défilent et j'ai laissé tourné toute la nuit. Aprés plusieurs essais j'ai decidé de ne pas installer sendbox et le probleme se décale, impossible de finir l'installation . Merci par avance
![Capture d’écran 2020-10-29 à 19 33 31](https://user-images.githubusercontent.com/50988506/97742380-7ef84e80-1ae4-11eb-9427-1b9f8b1e2330.png)

**Comment by toulousain79** [comment]
Salut,
Merci pour ton retour.
Cakebox et Seedbox-Manager sont confrontés au même problème, le binaire composer qui a évolué si je dis pas de bêtises.
Pour l'instant je n'ai pas trop le temps de corriger le problème.
J'ai donc désactiver l'installation de Cakebox et Seedbox-Manager.
