### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by shaine93** [toulousain79/MySB#121]
## Description simple du problème
Erreur sur dnscrypt-proxy lors d'une commande de mises a jours des règles .
Une description claire et concise du problème que tu rencontres.
Lorsque que je fais la commande My_SecurityRules Create il y a une erreur sur dsncrypt-proxy et Rutorrent est en panne
## Reproduction du problème

Étapes pour reproduire le problème:

1.dans le terminal lancer la commande My_SecurityRules Create

## Comportement prévisible

Une description claire et concise de ce à quoi tu t'attendais.

## Captures d'écran

Si possible, ajoutes des captures d'écran pour expliquer ton problème.

## Logs

Si possible, ajoutes des logs, ceux se trouvant dans **/opt/MySB/logs**.
------------------------------------------------------------ 
START Out/Err: 2021-06-09 - 17:11:29 - MySB_SecurityRules refresh --letsencrypt CRON 
------------------------------------------------------------ 
IPtables - Sauvegarde des règles:. 
IPtables - Actualisation des règles pour Let's Encrypt: failed! 
IPtables - Restauration des règles:iptables-restore: line 1 failed 
. 
---- 17:11:29 
Redémarrage de cron:. 
---- 17:11:29 
------------------------------------------------------------ 
END Out/Err: 2021-06-09 - 17:11:30 - MySB_SecurityRules refresh --letsencrypt CRON 
------------------------------------------------------------ 
------------------------------------------------------------ 
START Out/Err: 2021-06-09 - 17:11:40 - MySB_SecurityRules refresh --letsencrypt CRON 
------------------------------------------------------------ 
IPtables - Sauvegarde des règles:. 
IPtables - Actualisation des règles pour Let's Encrypt: failed! 
IPtables - Restauration des règles:. 
---- 17:11:40 
Redémarrage de cron:. 
---- 17:11:40 
------------------------------------------------------------ 
END Out/Err: 2021-06-09 - 17:11:41 - MySB_SecurityRules refresh --letsencrypt CRON 
------------------------------------------------------------ 
------------------------------------------------------------ 
START Out/Err: 2021-06-09 - 17:43:49 - MySB_SecurityRules create INSTALL 
------------------------------------------------------------ 
---- 17:43:50 
Arrêt de rtorrent-lolufe:. 
Arrêt de PeerGuardian Linux: pglcmd. 
Arrêt de fail2ban:. 
Arrêt de cron:. 
Service déjà arrêté: nfs-kernel-server. 
Arrêt de smbd:. 
Arrêt de openvpn:. 
Service déjà arrêté: dnscrypt-proxy. 
---- 17:43:53 
Kernel   - Chargement des modules:. 
Kernel   - Configuration des paramètres:. 
IPtables - Suppression des règles existantes:. 
IPtables - Interdiction de toutes les connexions entrantes/sortantes:. 
IPtables - Création de chaînes utilisateur:. 
IPtables - Remplissage de la chaîne BAD:. 
IPtables - Remplissage de la chaîne ICMP (pour les utilisateurs et HETZNER):. 
IPtables - Remplissage de la chaîne de UDP entrante:. 
IPtables - Remplissage de la chaîne de UDP sortante:. 
IPtables - Remplissage de la chaîne de TCP entrante:. 
IPtables - Remplissage de la chaîne de TCP sortante:. 
IPtables - Processus de la chaîne INPUT:. 
IPtables - Processus de la chaîne FORWARD:. 
IPtables - Processus de la chaîne OUTPUT:. 
IPtables - Processus de la chaîne NAT PREROUTING:. 
IPtables - Processus de la chaîne NAT POSTROUTING:. 
IPtables - Processus de la chaîne NAT OUTPUT:. 
IPtables - Processus des chaînes DOCKER:. 
NginX - Autorisation des adresses IP de tous les utilisateurs:. 
NginX - Autorisation des adresses IP locales d'OpenVPN:. 
NginX - Autorisation de l'interface de bouclage:. 
Bind     - Blocage de toutes les demandes sortantes des trackers inactifs:. 
Bind     - Ajout des trackers actifs dans le fichier 'hosts':. 
Fail2Ban - Ajout des adresses IP à la liste blanche:. 
---- 17:44:07 
Rechargement de bind9:. 
Rechargement de nginx:. 
Démarrage de fail2ban:. 
Démarrage de PeerGuardian Linux:. 
Utilisation des listes de blocage avec PeerGuardian: lolufe. 
Démarrage de openvpn:. 
Démarrage de smbd:. 
Démarrage de nfs-kernel-server:. 
Démarrage de rtorrent-lolufe:. 
---- 17:44:13 
-------------------- 
Configuration des liaisons dynamiques (ldconfig):. 
Nettoyage du cache système:. 
------------------------------------------------------------ 
END Out/Err: 2021-06-09 - 17:44:15 - MySB_SecurityRules create INSTALL 
------------------------------------------------------------ 
------------------------------------------------------------ 
START Out/Err: 2021-06-09 - 17:45:28 - MySB_SecurityRules create INIT 
------------------------------------------------------------ 
---- 17:45:28 
Service déjà arrêté: rtorrent-lolufe. 
Service déjà arrêté: pglcmd. 
Service déjà arrêté: fail2ban. 
Service déjà arrêté: cron. 
Service déjà arrêté: nfs-kernel-server. 
Service déjà arrêté: smbd. 
Service déjà arrêté: openvpn. 
---- 17:45:28 
Kernel   - Chargement des modules:. 
Kernel   - Configuration des paramètres:. 
IPtables - Suppression des règles existantes:. 
IPtables - Interdiction de toutes les connexions entrantes/sortantes:. 
IPtables - Création de chaînes utilisateur:. 
IPtables - Remplissage de la chaîne BAD:. 
IPtables - Remplissage de la chaîne ICMP (pour les utilisateurs et HETZNER):. 
IPtables - Remplissage de la chaîne de UDP entrante:. 
IPtables - Remplissage de la chaîne de UDP sortante:. 
IPtables - Remplissage de la chaîne de TCP entrante:. 
IPtables - Remplissage de la chaîne de TCP sortante:. 
IPtables - Processus de la chaîne INPUT:. 
IPtables - Processus de la chaîne FORWARD:. 
IPtables - Processus de la chaîne OUTPUT:. 
IPtables - Processus de la chaîne NAT PREROUTING:. 
IPtables - Processus de la chaîne NAT POSTROUTING:. 
IPtables - Processus de la chaîne NAT OUTPUT:. 
IPtables - Processus des chaînes DOCKER:. 
NginX - Autorisation des adresses IP de tous les utilisateurs:. 
NginX - Autorisation des adresses IP locales d'OpenVPN:. 
NginX - Autorisation de l'interface de bouclage:. 
Bind     - Blocage de toutes les demandes sortantes des trackers inactifs:. 
Bind     - Ajout des trackers actifs dans le fichier 'hosts':. 
Fail2Ban - Ajout des adresses IP à la liste blanche:. 
---- 17:45:43 
Démarrage de cron:. 
Rechargement de bind9:. 
Rechargement de nginx:. 
Démarrage de fail2ban:. 
Démarrage de PeerGuardian Linux:. 
Utilisation des listes de blocage avec PeerGuardian: lolufe. 
Démarrage de openvpn:. 
Démarrage de smbd:. 
Démarrage de nfs-kernel-server:. 
Démarrage de dnscrypt-proxy:Job for dnscrypt-proxy.service failed because the control process exited with error code. 
See "systemctl status dnscrypt-proxy.service" and "journalctl -xe" for details. 
 failed! 
---- 17:45:45 
------------------------------------------------------------ 
END Out/Err: 2021-06-09 - 17:45:46 - MySB_SecurityRules create INIT 
------------------------------------------------------------ 

## Matériel et environnement

- Hébergeur: _Hetzner
- Type de serveur: _Dédié
- Version de MySB: _V7.3
![Capture d’écran 2021-06-10 à 16 27 23](https://user-images.githubusercontent.com/50988506/121543080-ee360980-ca08-11eb-8ff2-3f5a06310a0b.png)
![Capture d’écran 2021-06-10 à 16 27 04](https://user-images.githubusercontent.com/50988506/121543087-ef673680-ca08-11eb-861e-c0d627a9c4b1.png)

- Version du noyau: _(uname -a)_
- Matériel: _(CPU, RAM, HDD, Raid, ...)_

## Contexte supplémentaire

Si nécessaire, ajoutes un autre contexte concernant le problème ici.

**Comment by toulousain79** [comment]
Some parameters and elements of DNScrypt have been modified since version 2.0.45 making the MySB installation non-functional.

Some examples:

- [blacklist] has been renamed to [blocked_names]
- [ip_blacklist] has been renamed to [blocked_ips]
- [whitelist] has been renamed to [allowed_names]

Some fixes have also been applied such as:

- Certbot (Let's Encrypt) sources list
- PiP parameter
