### ISSUE TITLE
Error on seedbox manager and MySB

### ISSUE THREAD

**Issue by fravia1** [toulousain79/MySB#13]
On seedbon manager this error gets generated , previously it was working fine. 
Installation Guide

Starting the application
Indicate the correct owner of the files of the application, copy the command and run it ROOT (super user).

chown -R www-data: www-data / etc / MySB / web / seedbox-manager /
Run the install.sh script to compile the reboot program ROOT.

cd / etc / MySB / web / seedbox-manager / source-reboot-rtorrent /
chmod + x install.sh ./install.sh &&

on mySB portal
Wolf CMS automatically disabled!

Wolf CMS has been disabled as a security precaution.

Reason: the configuration file was found to be writable.

The broadest rights Wolf CMS allows for config.php are: -rwxr-xr-x

**Comment by fravia1** [comment]
I think you made some recent updates hope that is not the cause for this.

**Comment by toulousain79** [comment]
Please execute 'MySB_GitHubRepoUpdate'. This command will change owners et rights for some files and directories. Check the last line of prompt.

What manipulations or commands have you done for the rights of certain files disappear?

Tell if is OK.

**Comment by toulousain79** [comment]
Have you checked the issue 10?
https://github.com/toulousain79/MySB/issues/10

**Comment by toulousain79** [comment]
I did not change anything concerning rights of files. The only changes concern some templates (unused for now), and the file 'funcs_iptables'.
By running the command 'MySB_GithubUpdate' you will see the files.

**Comment by fravia1** [comment]
MySB_GithubUpdate command generates the following response -bash: MySB_GithubUpdate: command not found

**Comment by toulousain79** [comment]
Try the full command:
bash /etc/MySB/bin/MySB_GitHubRepoUpdate

**Comment by fravia1** [comment]
Saved working directory and index state WIP on v2.0: 5d11656 v2.1
HEAD is now at 5d11656 v2.1
error: Couldn't resolve host 'github.com' while accessing https://github.com/toulousain79/MySB.git/info/refs
fatal: HTTP request failed
[ ok ] Change owners and rights for files and directories:.

**Comment by fravia1** [comment]
The situation persists.

**Comment by toulousain79** [comment]
service bind9 restart
and
bash /etc/MySB/bin/MySB_SecurityRules create

**Comment by fravia1** [comment]
[FAIL] Starting domain name service...: bind9 failed!

**Comment by toulousain79** [comment]
Did you change something with bind (trackers) ?

Give me the last lines of this file:
tail -n 20 /var/log/bind/global.log

**Comment by fravia1** [comment]
Well It was completely untouched.

**Comment by toulousain79** [comment]
OK, please give me the result of:
tail -n 20 /var/log/bind/global.log

**Comment by fravia1** [comment]
I made 7 reinstalls on my server , so definitely not a change that i had made.

**Comment by fravia1** [comment]
I can uninstall bind and re install it , if that would work?

**Comment by toulousain79** [comment]
NO
Try this: bash /raid0/MySB/install/Bind

**Comment by fravia1** [comment]
bash: /raid0/MySB/install/Bind: No such file or directory

**Comment by toulousain79** [comment]
Sorry, '/raid0/MySB' is my configuration.

This one is the default directory:
bash /etc/MySB/install/Bind

**Comment by fravia1** [comment]
aptitude -q -y --assume-yes -o Acquire::Check-Valid-Until=false update
Err http://ftp.nerim.net wheezy Release.gpg
  Could not resolve 'ftp.nerim.net'
Err http://ftp.fr.debian.org wheezy Release.gpg
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.proxad.net wheezy Release.gpg
  Could not resolve 'ftp.proxad.net'
Err http://debian.mirrors.easynet.fr wheezy Release.gpg
  Could not resolve 'debian.mirrors.easynet.fr'
Err http://security.debian.org wheezy/updates Release.gpg
  Could not resolve 'security.debian.org'
Err http://packages.dotdeb.org wheezy Release.gpg
  Could not resolve 'packages.dotdeb.org'
Err http://packages.dotdeb.org wheezy-php55 Release.gpg
  Could not resolve 'packages.dotdeb.org'
Err http://moblock-deb.sourceforge.net wheezy Release.gpg
  Could not resolve 'moblock-deb.sourceforge.net'
Err http://download.webmin.com sarge Release.gpg
  Could not resolve 'download.webmin.com'
Err http://shell.ninthgate.se wheezy Release.gpg
  Could not resolve 'shell.ninthgate.se'
Reading package lists...
W: Failed to fetch http://ftp.nerim.net/debian/dists/wheezy/Release.gpg: Could not resolve 'ftp.nerim.net'
W: Failed to fetch http://ftp.fr.debian.org/debian/dists/wheezy/Release.gpg: Could not resolve 'ftp.fr.debian.org'
W: Failed to fetch http://ftp.proxad.net/mirrors/ftp.debian.org/dists/wheezy/Release.gpg: Could not resolve 'ftp.proxad.net'
W: Failed to fetch http://debian.mirrors.easynet.fr/debian/dists/wheezy/Release.gpg: Could not resolve 'debian.mirrors.easynet.fr'
W: Failed to fetch http://security.debian.org/dists/wheezy/updates/Release.gpg: Could not resolve 'security.debian.org'
W: Failed to fetch http://packages.dotdeb.org/dists/wheezy/Release.gpg: Could not resolve 'packages.dotdeb.org'
W: Failed to fetch http://packages.dotdeb.org/dists/wheezy-php55/Release.gpg: Could not resolve 'packages.dotdeb.org'
W: Failed to fetch http://moblock-deb.sourceforge.net/debian/dists/wheezy/Release.gpg: Could not resolve 'moblock-deb.sourceforge.net'
W: Failed to fetch http://shell.ninthgate.se/packages/debian/dists/wheezy/Release.gpg: Could not resolve 'shell.ninthgate.se'
W: Failed to fetch http://download.webmin.com/download/repository/dists/sarge/Release.gpg: Could not resolve 'download.webmin.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
UPDATE system SET apt_update = 0, apt_date = datetime('now','localtime') WHERE id_system = 1;
aptitude -q -y --assume-yes install bind9
Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Writing extended state information...
Reading task descriptions...
The following NEW packages will be installed:
  bind9 [1:9.8.4.dfsg.P1-6+nmu2+deb7u4]
0 packages upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 374 kB of archives. After unpacking 984 kB will be used.
Writing extended state information...
Err http://security.debian.org/ wheezy/updates/main bind9 amd64 1:9.8.4.dfsg.P1-6+nmu2+deb7u4
  Could not resolve 'security.debian.org'
E: Failed to fetch http://security.debian.org/pool/updates/main/b/bind9/bind9_9.8.4.dfsg.P1-6+nmu2+deb7u4_amd64.deb: Could not resolve 'security.debian.org'
Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Reading task descriptions...
aptitude -q -y --assume-yes autoremove
Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...

**Comment by toulousain79** [comment]
sed -i '/nameserver/d' /etc/resolv.conf
echo "nameserver 208.67.220.220" >> /etc/resolv.conf
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
echo "nameserver 4.2.2.1" >> /etc/resolv.conf

bash /etc/MySB/install/Bind

bash /etc/MySB/bin/MySB_SecurityRules create

**Comment by fravia1** [comment]
[ ok ] Service already stopped: bind9.
include "/etc/bind/zones.rfc1918";
include "/etc/bind/rndc.key";
include "/etc/bind/bind.keys";
include "/etc/bind/log.conf";
include "/etc/bind/MySB.zones.blakclists";
removed `/etc/bind/log.conf'
logging {
        channel "requetes" {
                file "/var/log/bind/queries.log";
                print-time yes;
                print-category yes;
        };
        category queries { "requetes"; };

        channel "security" {
                file "/var/log/bind/security.log";
                print-category yes;
                print-severity yes;
                print-time yes;
        };
        category security { "security"; };

        channel "global" {
                file "/var/log/bind/global.log";
                print-category yes;
                print-severity yes;
                print-time yes;
        };
        category general { "global"; };

        channel "configuration" {
                file "/var/log/bind/config.log";
                print-category yes;
                print-severity yes;
                print-time yes;
        };
        category config { "configuration"; };
};
#### MySB - Blacklisted domains (ex: inactive trackers)
removed `/etc/logrotate.d/bind'
/var/log/bind/*.log {
        weekly
        missingok
        rotate 10
        compress
        delaycompress
        create 775 root bind
        postrotate
        /etc/init.d/bind9 reload > /dev/null
        endscript
}

update-rc.d: using dependency based boot sequencing
[FAIL] Starting domain name service...: bind9 failed!
bind9 is not running ... failed!

**Comment by toulousain79** [comment]
Please, give me result of
tail -n 20 /var/log/bind/global.log

**Comment by fravia1** [comment]
I gave up , went for a re install :(

**Comment by fravia1** [comment]
I will install the script on a new server and update you.

**Comment by toulousain79** [comment]
Done in version 2.1
