### ISSUE TITLE
Error with LoadAVG

### ISSUE THREAD

**Issue by NouRs0n** [toulousain79/MySB#14]
Hi, 
For start, sorry for my english (Toulousain inside) ^^

I take error when i would launch LoadAVG:
/loadavg/public/index.php
La page n'est pas redirigée correctement

If i change "public" by my user, don't work too... 

And for finish very very thanks for this beautyful script (i Forked them for translate the home page in french, if you are ok with that)

**Comment by toulousain79** [comment]
Salut,

Je suis français ;-)

Je suis au courant pour le problème, je l'ai corrigé dans la v2.1 qui ne devrait plus tarder.
Je pense la valider sûrement ce weekend.

Pour la traduction, pourquoi pas. Cela fait parti de mon ToDo mais n'est pas une priorité.
Donc si vous avancez sur le sujet, je pourrais l'intégrer dans une future version.

bye

**Comment by NouRs0n** [comment]
Génial, que ca soit par la resolution de ce bug ou votre accord afin de pouvoir le traduire. (de surcroit le fait que vous soyez Français, cela facilitera mes quelques interrogations.)
En tout cas, j'adore votre script qui me facilite la vie :-)

**Comment by toulousain79** [comment]
Merci.

J'ai intégré les corrections v2.1 de LoadAvg dans la v2.0.
Pour l'appliquer, faites ceci:
MySB_GitHubRepoUpdate
MySB_RefreshMe loadavg

**Comment by toulousain79** [comment]
Avant n'oubliez pas d'annuler les modifications que vous avez appliquées.

**Comment by NouRs0n** [comment]
Marche parfaitement, j'ai pleinement acces à LoadAVG.

Grand merci :)

**Comment by NouRs0n** [comment]
Je reste sur ce thread car je pense pas que cela soit une autre "issue". J'ai trouvé des fichiers de plus de 3Go dans le dossier /var/log  (en Mo)
2858    ./var/log/debug
2861    ./var/log/syslog
2864    ./var/log/kern.log
Est-ce normal qu'ils soient si gros? Peut on les vider?

**Comment by toulousain79** [comment]
Etes-vous certain que vos fichiers font 3 Go ? Un fichier de log de cette taille n'est pas spécialement gênant, cela dépend effectivement du fichier.
Mais cela me parait étrange pour un serveur que vous venez d'installer. Voici le listing de mon serveur tournant de puis quelques mois.

root@mysb:/var/log# ls -lah
total 210M
drwxr-xr-x 14 root        root     4,0K mai    1 06:35 .
drwxr-xr-x 12 root        root     4,0K févr. 22 13:57 ..
-rw-r--r--  1 root        root        0 mai    1 06:35 alternatives.log
-rw-r--r--  1 root        root      170 avril  5 17:59 alternatives.log.1
-rw-r--r--  1 root        root      129 mars  24 13:29 alternatives.log.2.gz
-rw-r--r--  1 root        root      129 mars  13 13:33 alternatives.log.3.gz
-rw-r--r--  1 root        root     1,3K févr. 24 09:06 alternatives.log.4.gz
drwxr-xr-x  2 root        root     4,0K mai    1 06:35 apt
-rw-r--r--  1 root        root        0 mai    1 06:35 aptitude
-rw-r--r--  1 root        root     1,1K mai    1 00:41 aptitude.1.gz
-rw-r--r--  1 root        root      690 mars  24 13:29 aptitude.2.gz
-rw-r--r--  1 root        root      522 mars  13 13:32 aptitude.3.gz
-rw-r--r--  1 root        root     3,1K févr. 24 09:05 aptitude.4.gz
-rw-r-----  1 root        adm      2,3M mai    1 11:21 auth.log
-rw-r-----  1 root        adm      3,0M avril 26 06:30 auth.log.1
-rw-r-----  1 root        adm      139K avril 19 06:45 auth.log.2.gz
-rw-r-----  1 root        adm      136K avril 12 06:39 auth.log.3.gz
-rw-r-----  1 root        adm      136K avril  5 06:50 auth.log.4.gz
drwxr-xr-x  2 bind        bind     4,0K avril 26 06:34 bind
-rw-rw----  1 root        utmp        0 mai    1 06:35 btmp
-rw-rw----  1 root        utmp        0 avril  1 06:39 btmp.1
-rw-r-----  1 root        adm       37K mai    1 06:39 daemon.log
-rw-r-----  1 root        adm       51K avril 26 06:34 daemon.log.1
-rw-r-----  1 root        adm      9,5K avril 19 06:46 daemon.log.2.gz
-rw-r-----  1 root        adm      6,4K avril 12 06:39 daemon.log.3.gz
-rw-r-----  1 root        adm      5,0K avril  5 06:52 daemon.log.4.gz
-rw-r-----  1 root        adm      244K mai    1 10:44 debug
-rw-r-----  1 root        adm      135K avril 26 06:25 debug.1
-rw-r-----  1 root        adm       33K avril 19 06:25 debug.2.gz
-rw-r-----  1 root        adm       20K avril 12 06:25 debug.3.gz
-rw-r-----  1 root        adm      220K avril  5 06:25 debug.4.gz
-rw-r-----  1 root        adm       57K avril 14 23:14 dmesg
-rw-r-----  1 root        adm       58K avril 13 21:42 dmesg.0
-rw-r-----  1 root        adm       15K mars  22 20:00 dmesg.1.gz
-rw-r-----  1 root        adm       15K févr. 24 09:26 dmesg.2.gz
-rw-r-----  1 root        adm       15K févr. 23 22:49 dmesg.3.gz
-rw-r-----  1 root        adm       15K févr. 22 14:46 dmesg.4.gz
drwxr-xr-x  3 root        root     4,0K mars  22 15:11 dnscrypt-proxy
-rw-r--r--  1 root        root        0 mai    1 06:35 dpkg.log
-rw-r--r--  1 root        root      34K avril 14 13:50 dpkg.log.1
-rw-r--r--  1 root        root     2,2K mars  24 13:29 dpkg.log.2.gz
-rw-r--r--  1 root        root     1,5K mars  13 13:33 dpkg.log.3.gz
-rw-r--r--  1 root        root      19K févr. 24 09:06 dpkg.log.4.gz
drwxr-s---  2 Debian-exim adm      4,0K mars  13 13:50 exim4
-rw-r-----  1 root        adm       27K mai    1 06:35 fail2ban.log
-rw-r-----  1 root        adm       36K avril 25 15:50 fail2ban.log.1
-rw-r-----  1 root        adm      8,7K avril 18 19:46 fail2ban.log.2.gz
-rw-r-----  1 root        adm      9,4K avril 11 21:58 fail2ban.log.3.gz
-rw-r-----  1 root        adm      1020 avril  4 18:38 fail2ban.log.4.gz
-rw-r--r--  1 root        root      32K févr. 23 18:48 faillog
-rw-r--r--  1 root        root      409 févr. 22 13:28 fontconfig.log
drwxr-xr-x  2 root        root     4,0K oct.  10  2012 fsck
-rw-r-----  1 root        adm       49M mai    1 11:22 kern.log
-rw-r-----  1 root        adm       35M avril 26 06:34 kern.log.1
-rw-r-----  1 root        adm      2,2M avril 19 06:46 kern.log.2.gz
-rw-r-----  1 root        adm      2,5M avril 12 06:39 kern.log.3.gz
-rw-r-----  1 root        adm      2,7M avril  5 06:52 kern.log.4.gz
-rw-rw-r--  1 root        utmp     287K mai    1 11:21 lastlog
-rw-r-----  1 root        adm         0 févr. 10  2014 lpr.log
-rw-r-----  1 root        adm         0 févr. 10  2014 mail.err
-rw-r-----  1 root        adm       13K mai    1 06:39 mail.info
-rw-r-----  1 root        adm       16K avril 26 06:25 mail.info.1
-rw-r-----  1 root        adm      2,6K avril 19 06:25 mail.info.2.gz
-rw-r-----  1 root        adm      4,0K avril 12 06:25 mail.info.3.gz
-rw-r-----  1 root        adm      4,2K avril  5 06:25 mail.info.4.gz
-rw-r-----  1 root        adm       13K mai    1 06:39 mail.log
-rw-r-----  1 root        adm       16K avril 26 06:25 mail.log.1
-rw-r-----  1 root        adm      2,6K avril 19 06:25 mail.log.2.gz
-rw-r-----  1 root        adm      4,0K avril 12 06:25 mail.log.3.gz
-rw-r-----  1 root        adm      4,2K avril  5 06:25 mail.log.4.gz
-rw-r-----  1 root        adm         0 mars  29 06:26 mail.warn
-rw-r-----  1 root        adm      3,2K mars  23 11:00 mail.warn.1
-rw-r-----  1 root        adm       391 mars  23 06:25 mail.warn.2.gz
-rw-r-----  1 root        adm       217 févr. 23 12:13 mail.warn.3.gz
-rw-r-----  1 root        adm       53M mai    1 11:22 messages
-rw-r-----  1 root        adm       40M avril 26 06:34 messages.1
-rw-r-----  1 root        adm      2,3M avril 19 06:46 messages.2.gz
-rw-r-----  1 root        adm      2,7M avril 12 06:39 messages.3.gz
-rw-r-----  1 root        adm      2,7M avril  5 06:53 messages.4.gz
drwxr-xr-x  2 root        root     4,0K avril 15  2013 news
drwxr-x---  2 www-data    adm      4,0K mai    1 06:35 nginx
drwxr-xr-x  2 ntp         ntp      4,0K févr.  7 12:05 ntpstats
drwxr-xr-x  2 root        root     4,0K mars  22 19:51 openvpn
drwxr-xr-x  2 root        root     4,0K mai    1 06:35 pgl
-rw-------  1 root        root       56 avril 26 06:34 php5-fpm.log
-rw-------  1 root        root       56 avril 19 06:46 php5-fpm.log.1
-rw-------  1 root        root      694 févr. 27 12:59 php5-fpm.log.10.gz
-rw-------  1 root        root      239 avril 14 23:14 php5-fpm.log.2.gz
-rw-------  1 root        root      238 avril  5 17:59 php5-fpm.log.3.gz
-rw-------  1 root        root      298 avril  2 10:33 php5-fpm.log.4.gz
-rw-------  1 root        root      273 mars  24 13:29 php5-fpm.log.5.gz
-rw-------  1 root        root       76 mars  15 06:27 php5-fpm.log.6.gz
-rw-------  1 root        root       76 mars  13 13:50 php5-fpm.log.7.gz
-rw-------  1 root        root      239 mars  13 13:33 php5-fpm.log.8.gz
-rw-------  1 root        root       76 mars   1 06:34 php5-fpm.log.9.gz
-rw-r--r--  1 root        root        0 févr. 22 13:23 pycentral.log
-rw-r-----  1 root        adm         0 mars   1 06:34 rkhunter.log
-rw-------  1 root        root     114K févr. 22 13:23 rkhunter.log.1
-rw-------  1 root        root     3,6K févr. 22 13:21 rkhunter.log.old
drwxr-x---  3 root        adm      4,0K avril 26 06:34 samba
drwxr-xr-x  2 stunnel4    stunnel4 4,0K févr. 24 06:26 stunnel4
-rw-r-----  1 root        adm      1,4M mai    1 11:22 syslog
-rw-r-----  1 root        adm      6,7M mai    1 06:35 syslog.1
-rw-r-----  1 root        adm      662K avril 30 06:45 syslog.2.gz
-rw-r-----  1 root        adm      658K avril 29 06:29 syslog.3.gz
-rw-r-----  1 root        adm      775K avril 28 06:39 syslog.4.gz
-rw-r-----  1 root        adm      2,3M avril 27 06:40 syslog.5.gz
-rw-r-----  1 root        adm      478K avril 26 06:34 syslog.6.gz
-rw-r-----  1 root        adm      523K avril 25 06:36 syslog.7.gz
-rw-r-----  1 root        adm         0 avril 15 06:53 user.log
-rw-r-----  1 root        adm        69 avril 14 23:12 user.log.1
-rw-r-----  1 root        adm       270 mars  22 19:58 user.log.2.gz
-rw-r-----  1 root        adm       316 févr. 24 09:24 user.log.3.gz
-rw-r-----  1 root        adm         0 avril 26 06:34 vsftpd.log
-rw-r-----  1 root        adm      2,5K avril 26 06:34 vsftpd.log.1
-rw-r-----  1 root        adm       799 avril 23 21:32 vsftpd.log.2
-rw-r-----  1 root        adm       306 avril 13 23:40 vsftpd.log.3
-rw-r-----  1 root        adm      1,7K avril  2 19:23 vsftpd.log.4
-rw-rw-r--  1 root        utmp      384 mai    1 11:21 wtmp
-rw-rw-r--  1 root        utmp      55K mai    1 01:21 wtmp.1

**Comment by toulousain79** [comment]
Quelle fournisseur avez-vous, quel serveur?
Et comment avez-vous partitionné votre disque?

**Comment by NouRs0n** [comment]
Bonjour,
J'ai passé une partie de la nuit à faire dossier par dossier du serveur afin de trouver "les fichiers" qui surcharger le disque...
Dans la nuit je me suis retrouver avec a peine 40Mo de libre sur le HDD, puis j'ai fini par abandonner ne trouvant pas de raison valable... Je viens de me remettre à l'ordi, j'ouvre de suite MySB portal et là le disque est plein à 21% ce qui est bien plus adequat, à mon sens.

Sinon, pour repondre à votre question, fournisseur OVH (kimsufi 2g)
sda      8:0    0 931,5G  0 disk
├─sda1   8:1    0  19,5G  0 part /
├─sda2   8:2    0     2G  0 part [SWAP]
└─sda3   8:3    0   910G  0 part /home

Pour les partitions
