### ISSUE TITLE
Erreur aprés Mise à jour

### ISSUE THREAD

**Issue by NouRs0n** [toulousain79/MySB#15]
Salut,
Alors, la mise à jour c'est tres bien passer. Il y a juste une erreur à la fin de la MaJ:
Updating MySB version...Done !
Upgrade script does not exist (/etc/MySB/upgrade/From_v2.0-to-v2.1.bsh), aborting...
-bash: /etc/MySB/bin/MySB_UpgradeMe: Permission non accordée

Je presume qu'il n'a pas du remettre les droits, car les scripts sont bien present.
/etc/MySB/bin# ls
MySB_ChangeUserPassword  MySB_GitHubRepoUpdate  MySB_UpgradeMe
MySB_CreateUser          MySB_RefreshMe         MySB_UpgradeSystem
MySB_DeleteUser          MySB_SecurityRules

**Comment by toulousain79** [comment]
Salut,

 

Merci pour votre retour.

 

Donc la MàJ ne sait pas bien passée pour vous.

Car si le script /etc/MySB/upgrade/From_v2.0-to-v2.1.bsh n’a pas été exécuté tous le processus de mise à jour ne sait pas fait …

Le message Updating MySB version...Done ! n’est que le début… (préparation)

Vous auriez-du avoir la même chose que la copie d’écran ci-dessous

 

Si ce script n’a pas été trouvé, c’est qu’il n’a pas été téléchargé via MySB_GitHubRepoUpdate causé je pense par un blocage du couple Bind/DNScrypt.

Lors de mes tests sur ma machine virtuelle, j’ai rencontré se problème car la synchro NTP ne se faisait pas…

Et DNSEC bloquait les requêtes sortantes car il y a avait un trop écart de temps.

 

De mon côté, la MàJ s’est bien déroulée (serveur de production) SAUF à la fin lorsqu’il a fallu restaurer les règles de sécurité. J’ai perdu la main et j’ai dû redémarrer le serveur via l’interface OVH.

D’après les logs, cela a merdouillé au moment de redémarrage de DNScrypt-proxy, et je ne sais pas pourquoi….

J’ai modifié une partie du process de boot des services lorsque le serveur démarre. Le but étant de forcer la création de toutes les règles de sécurité lors d’un boot (heureusement).

 

Reloading domain name service...: bind9.

Restarting OpenDNS DNScrypt-proxy: dnscrypt-proxy------------------------------------------------------------

START Out/Err: Sun May 3 12:41:17 CEST 2015 - MySB_SecurityRules create

------------------------------------------------------------

 

 

 



 

De : NouRs0n [mailto:notifications@github.com] 
Envoyé : dimanche 3 mai 2015 12:43
À : toulousain79/MySB
Objet : [MySB] Erreur Mise à jour (#15)

 

Salut,
Alors, la mise à jour c'est tres bien passer. Il y a juste une erreur à la fin de la MaJ:
Updating MySB version...Done !
Upgrade script does not exist (/etc/MySB/upgrade/From_v2.0-to-v2.1.bsh), aborting...
-bash: /etc/MySB/bin/MySB_UpgradeMe: Permission non accordée

Je presume qu'il n'a pas du remettre les droits, car les scripts sont bien present.
/etc/MySB/bin# ls
MySB_ChangeUserPassword MySB_GitHubRepoUpdate MySB_UpgradeMe
MySB_CreateUser MySB_RefreshMe MySB_UpgradeSystem
MySB_DeleteUser MySB_SecurityRules

—
Reply to this email directly or view it on GitHub <https://github.com/toulousain79/MySB/issues/15> .  <https://github.com/notifications/beacon/AHIm_Lfz83j_ywagPx7RB3jbzcIQrh0Iks5oFfM1gaJpZM4EOnbK.gif> 



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by NouRs0n** [comment]
Bonjour,

J'ai bien marquer 2.1 sur le portail de MySB, mais rutorrent en 3.6 (j'ai regardé le changelog histoire de voir si la MaJ c'etait bien faites, ou en partie)
Apres reboot, meme erreur pas possible de lancer le script de mise à jour.
Et je n'ai pas de log de MySB_UpgradeMe-log.html dans la section dédié à ça.
Quel droit dois-je accorder au script, je voudrai pas lui donner trop de droit que necessaire (ou pas assez)

**Comment by toulousain79** [comment]
Exécutez les commandes suivantes les unes après les autres.
source /etc/MySB/inc/vars
source /etc/MySB/inc/funcs
source /etc/MySB/inc/funcs_tools
SwitchDNS "standard"
MySB_GitHubRepoUpdate
bash /etc/MySB/upgrade/From_v2.0-to-v2.1.bsh

**Comment by NouRs0n** [comment]
à la commande: MySB_GitHubRepoUpdate
-bash: /etc/MySB/bin/MySB_GitHubRepoUpdate: Permission non accordée

**Comment by toulousain79** [comment]
Lancez une nouvelle instance avec Putty et essayez à nouveau avec une commande supplémentaire
source /etc/MySB/inc/vars
source /etc/MySB/inc/funcs
source /etc/MySB/inc/funcs_tools
ManageDirectoriesAndFiles
SwitchDNS "standard"
MySB_GitHubRepoUpdate
bash /etc/MySB/upgrade/From_v2.0-to-v2.1.bsh

**Comment by NouRs0n** [comment]
Le GitHubRepoUpdate, c'est bien passé mais c'est au lancement du script.
bash /etc/MySB/upgrade/From_v2.0-to-v2.1.bsh
bash: /etc/MySB/upgrade/From_v2.0-to-v2.1.bsh: Aucun fichier ou dossier de ce type

dans le dossier upgrade il n'y a que celui pour passer de 1.1 en 2.0
/etc/MySB/upgrade# ls
backup  From_v1.1-to-v2.0.bsh

**Comment by toulousain79** [comment]
OK, on avance...
Que vous donne '/etc/MySB/version' ?
Si le résultat est 'v2.1' alors je pense que vous pouvez exécuter la commande 'MySB_UpgradeMe' directement.

**Comment by NouRs0n** [comment]
/etc/MySB/version
/etc/MySB/version: ligne1: v2.0 : commande introuvable

**Comment by toulousain79** [comment]
Pardon c'est 'cat /etc/MySB/version'

**Comment by NouRs0n** [comment]
v2.0 quand meme :)

**Comment by toulousain79** [comment]
Cool, relancez la commande 'MySB_UpgradeMe'

**Comment by NouRs0n** [comment]
« /tmp/MySB_backup_20150503-140939 » -> « /etc/MySB/upgrade/backup »

Merge MySB to v2.0
Please wait  5 4 3 2 1 0
Fetching origin
error: Couldn't resolve host 'github.com' while accessing https://github.com/toulousain79/MySB.git/info/refs
fatal: HTTP request failed
error: Could not fetch origin
Saved working directory and index state WIP on v2.0: 3beaa49 v2.0
HEAD is now at 3beaa49 v2.0
fatal: A branch named 'v2.0' already exists.
error: Couldn't resolve host 'github.com' while accessing https://github.com/toulousain79/MySB.git/info/refs
fatal: HTTP request failed
Updating MySB version...Done !

Upgrade script does not exist (/etc/MySB/upgrade/From_v2.1-to-v2.0.bsh), aborting...

**Comment by toulousain79** [comment]
Avez-vous créée une nouvelle session SSH depuis l'exécution des commandes ?
source /etc/MySB/inc/vars
source /etc/MySB/inc/funcs
source /etc/MySB/inc/funcs_tools
...

Si vous faites un 'ping github.com' vous aurez une erreur j'imagine.
source /etc/MySB/inc/vars
source /etc/MySB/inc/funcs
source /etc/MySB/inc/funcs_tools
SwitchDNS "standard"

Puis un nouveau 'ping github.com', qu'avez-vous comme résultat ?

**Comment by NouRs0n** [comment]
Oui je suis bien sur une autre session SSH

Aprés la serie de commande, le ping repond:
64 bytes from github.com (192.30.252.130): icmp_req=1 ttl=55 time=106 ms

**Comment by NouRs0n** [comment]
Une fois les commandes faite, je ne peux de nouveau plus lancer le MySB_UpgradeMe
De nouveau permission non accordée

**Comment by toulousain79** [comment]
J'ai modifié quelques lignes, essayez ceci
bash /etc/MySB/bin/MySB_GitHubRepoUpdate
PUIS
bash /etc/MySB/bin/MySB_UpgradeMe

**Comment by toulousain79** [comment]
Navré, j'ai fais une connerie (oubli), je ne pense pas que cela fonctionnera...
Seriez-vous OK pour me fournir un accès root à votre serveur pour que je puisse investiguer ?

**Comment by NouRs0n** [comment]
Oui il y a bien une erreur.
Je n'ai aucun probleme avec cela, accorder moi deux seconde que je mette un mot de passe en consequence.

**Comment by toulousain79** [comment]
J'ai trouvé l'erreur !
Laissez-moi l'après-midi que je puisse résoudre le problème, je dois m'absenter et je m'en occupe dès mon retour.
Attendez avant de m'envoyer votre accès, je n'en aurais peut-être pas besoin. Et si c'st le cas, je vous donnerez mon adresse mail direct. Je vous tiens au courant rapidement.

**Comment by NouRs0n** [comment]
D'accord, aucun probleme pour l'aprem, il n'y a aucune urgence je tenais à remonté ce petit probleme :)

Pas de soucis pour l'acces root, il s'agit d'un Dédié qui me sert à faire "mumuse". 

Excellente fin de dimanche profiter bien de votre journée :)

**Comment by toulousain79** [comment]
Re,
Je pense que c'est bon.
Essayez ceci SVP:
source /etc/MySB/inc/vars
source /etc/MySB/inc/funcs
source /etc/MySB/inc/funcs_tools
SwitchDNS "standard"
bash /etc/MySB/bin/MySB_GitHubRepoUpdate
bash /etc/MySB/bin/MySB_UpgradeMe

**Comment by NouRs0n** [comment]
Bonsoir, mes excuses je rentre à peine du taff.
à premiere vue, ca c'est bien passer:
Updating the clock...Done !
Updating actual GitHub repository........................................Done !
MySB is up to date !

**Comment by toulousain79** [comment]
Pas de soucis.
Il vous faut maintenant lancer manuellement le script d'upgrade.
bash /etc/MySB/upgrade/From_v2.0_to_v2.1.bsh

**Comment by NouRs0n** [comment]
bash /etc/MySB/upgrade/From_v2.0_to_v2.1.bsh
bash: /etc/MySB/upgrade/From_v2.0_to_v2.1.bsh: Aucun fichier ou dossier de ce type
ls /etc/MySB/upgrade
backup  From_v1.1-to-v2.0.bsh

Désolé, soit c'est moi qui est fait une couffe soit ce sont les manips faite precedement (debut de journée) qui ont peut etre perturber le truc.

**Comment by toulousain79** [comment]
Si vous n'avez rien cours je vous conseille d'installer la v2.1 sur un serveur propre.
Sinon je sais comment procéder mais je pourrais vous aiguiller demain qu'en fin de journée. Je suis sur mon téléphone et taper les commandes avec est peu pratique.

**Comment by NouRs0n** [comment]
aucun probleme, je pensais reprendre à zero toute facon. Comme je l'ai dit je fais mumuse :)

Bonne fin de nuit et merci pour le support ^^

**Comment by NouRs0n** [comment]
Réinstallation au propre en cours, mais probleme lors de la configuration du SMTP/EMAIL

Do you want to use an external SMTP server ? (Good for safe sending emails.).
Choose between LOCAL or listed providers FREE|OVH|GMAIL|YAHOO. Only SSL transactions will be used (SSL/465).
I recommend you to use a provider. This reduces the risk that the mails sent by the server is considered like spam.
You can change your choice later with the MySB portal.
What is your SMTP provider ?  LOCAL
Again: LOCAL
What's your e-mail address ? ********@grrlz.net
Again: ********@grrlz.net
What's your e-mail address ? ********@grrlz.net
Again: ********@grrlz.net
What's your e-mail address ? ********@gmail.com
Again: ********@gmail.com
What's your e-mail address ?

Malgres le fait de bien inserer deux fois la meme adresse, il ne la prend pas. J'ai cru que c'etait à cause de l'hebergeur pour la premiere mais ca le fait aussi sur une gmail.

**Comment by toulousain79** [comment]
Bonjour,
Ah, c'est un nouveau problème que je n'ai jamais rencontré. Je regarderai ma fonction.
Merci (navré que cette expérience MySB soit si compliquée, moi qui souhaite faire quelque chose de simple ET fonctionnel...)

**Comment by NouRs0n** [comment]
Don't worry :) faut bien paufiner les choses pour que cela soit, justement simple :)
Et puis l'avantage c'est que cela fait avancer les choses :D

(et Bonjour pardon, j'en oublie mes bonne manieres)

**Comment by NouRs0n** [comment]
Bon alors, j'ai refait a nouveau cela vient bien de la premiere adresse entrée (la GRRLZ) car la j'ai commencé direct par la GMAIL et c'est passé.

**Comment by toulousain79** [comment]
J'ai vérifié vite fait, la fonction de vérification des adresses mail utilise la commande DIG pour vérifier la validité du domaine, et vérifie l'argument 'ANSWER'.
La commande 'dig votre_domaine.net' renvoie 'ANSWER: 0' et pour gmail.com on obtient 'ANSWER: 1'.
La fonction valide le mail seulement si ANSWER = 1. Un enregistrement A doit être présent pour le domaine pour considérer la validité d'une adresse de ce domaine.
Avant de modifier le code, je vais analyser d'avantage pour savoir s'il est bien de retirer ou non le check avec DIG.

**Comment by NouRs0n** [comment]
Je comprend, Pour info, la boite mail que j'ai voulu utiliser pour le coup est heberger chez eux:
https://www.autistici.org/fr/index.html

**Comment by NouRs0n** [comment]
La 2.1 marche impecable sur une install fraiche :)

**Comment by toulousain79** [comment]
Tant mieux, c'est le but.
Il me reste donc à améliorer le script d'upgrade.

**Comment by NouRs0n** [comment]
Salut,
Je me permets de te relancer ici, car cela n'a rien à voir avec un problème.
Je voudrais avoir ton accord afin de présenter ton script, sur un petit forum sans prétention.
Si tu le permets je préparerai un "post" que tu pourras lire en amont si tu le désires bien entendu.

Merci d'avance pour ta réponse.

**Comment by toulousain79** [comment]
Salut,
Oui, pourquoi pas. C'est une bonne idée.

**Comment by NouRs0n** [comment]
Ok, je prepare le post, je t'en ferai part avant de le poster :)

**Comment by toulousain79** [comment]
Ça marche

**Comment by NouRs0n** [comment]
Je le poste là , il y a encore probablement des fautes, il y a probablement deux trois truc que je corrigerai, mais sur le principe il sera de cet ordre... (pour info il y a aussi des images, afin d’agrémenter mon post) j'ai directement mis en français simplement certaine partie du wiki, mais faut dire que c'est suffisamment clair pour ne pas avoir a être "ré-écrit"



Bonjour,
 
Je viens vous présenter un script sur lequel je suis tombé au court de mes pérégrination sur internet, à la recherche de la « facilité » n’y connaissant pas franchement grand-chose, ni en linux ni en ligne de commande et encore moins en « codage »… afin de configurer un serveur dédié
Nous sommes bien d’accord et surtout connaissons tous le script de Ex_Rat sur le forum de mondédié, étant formidable, il est difficile d’y trouver à redire… Mais j’aime fouiner et ne pas seulement me contenter d’une seule possibilité…
 
Et donc en fouinant sur GitHub je suis tombé sur celui-ci :
 
MySB
Créer par toulousain79
 
Je vais citer l’auteur pour decrire son projet:
“MySB est une seedbox multi-utilisateur pour un serveur dédié sous Debian 7 (Wheezy) et pourrai se renomer “MySSB”, My Secured SeedBox.”
 
L’intérêt de ce script c’est qu’il n’installe pas que rutorrent à l’instar de celui de ExRat_
Voici la liste de ce qu’il installe/configure/prépare :

    rTorrent (Rakshasa) v0.9.2 & v0.9.4 with SSL
    libTorrrent (Rakshasa) v0.13.2 & v0.13.4
    ruTorrent + official plugins (GIT)
    NginX (SSL, specific port and some customizations)
    PHP5-FPM (php5-apcu, FastCGI, SSL)
    SFTP with Chroot
    VSFTPd (FTP over TLS)
    Postfix with (or without) SMTP authentication (Gmail, Free, Ovh and Yahoo)
    PeerGuardian (optionnal but recommended)
    DNScrypt-proxy with Bind9 as DNS caching (optionnal but recommended)
    Fail2ban (optionnal but recommended)
    Seedbox-Manager (optionnal) (user interface is in french)
    LoadAvg (free server analytics and monitoring)
    OpenVPN (optionnal); Multi TUN/TAP configuration, with or without redirection of traffic. Add AES-NI support.
    Webmin (optionnal)
    CakeBox-Light (optionnal)
    PlexMedia Server (optionnal, VPN bridged access, requires additional setup)
    Samba share for each users (VPN access)
    NFS share for each users (VPN access)
    MySB portal (ability to manage trackers, blocklists, logs, users, restart rTorrent, switch of rTorrent version, and more)
    Special features of MySB
        Auto retrieve SSL certificates for all trackers (if available)
        Block all possibilities to use any listed trackers that was not activated in MySB portal
        BlockList usage (optionnal) (PeerGuardian or rTorrent, if PeerGuardian failed to start, rTorrent will use its own blocklists)
        Monitoring service available (OVH and Online)
        Access restricted by IP for all server access (can be disabled)
        Dynamic IP Management for IP restriction (DynDNS, No-IP, ...)




 
 
Comme vous pouvez le voir, on retrouve dans cette liste des outils qu’on connait bien mais aussi des services propres à MySB… Tel qu’un portail de gestion, diffèrent selon si on est l’utilisateur principal d’un utilisateur « normal ».
 
Bien entendu, chacun des services proposer n’est pas obligatoire, si l’on ne veut pas de plex ou de webmin (indiquer en OPTIONNAL).
 
La liste des plugins installés dans RuTorrent, en plus des officiels, avec le script sont ceux-ci :

[spoiler]

    Mobile
    Pause WebUI
    Chat
    Logoff
    tAdd-Labels
    Filemanager
    Mediastream
    Fileshare
    NFO
    RatioColor
    FileUpload
    Stream
    Favicons trackers

[/spoiler]


Voilà pour la présentation, maintenant les prérequis afin de rendre l’installation possible sur votre serveur Dédié.

    Les seuls impératifs sont d’utilisés le kernel par défaut du noyau et pas le custom de votre hébergeur. (Debian 7 Wheezy)
    Avoir une SWAP d’au moins 2Go pour le système (N’oubliez pas, que la taille de la SWAP doit être au moins égale a votre RAM)

Pour l’installation:
Connecter vous en ROOT grâce aux informations reçu à la livraison (ou réinstallation) de votre serveur (par mail souvent)
 
Puis copier-coller ceci dans votre terminal :

wget --no-check-certificate -N https://raw.githubusercontent.com/toulousain79/MySB/v2.1/install/MySB_Install.bsh

 
Puis une fois le téléchargement finit :

bash MySB_Install.bsh

 
De là, il n’y a plus qu’à se laisser guidé pas à pas …
 
L’installation prendra environs 30 à 60min selon votre serveur.
 
Si vous êtes déconnecté au cours de l’installation relancer la connexion SSH et rentrai ça :

screen -r MySB

 
 
À propos:

    L’installation est totalement silencieuse (screen) une fois les «questions» de préambule remplis, tous les logs d’installation seront à disposition sur le portail de MySB
    Lors de la création d’un utilisateur, un email de confirmation lui est envoyé avec un mot de passe «temporaire».
    À la fin de l’installation le serveur redémarrera de lui-même.
    D'autre ScreenShoot ici

**Comment by toulousain79** [comment]
Ok, quel est le forum?

**Comment by NouRs0n** [comment]
PassKey.fr on parle d'actu ciné musique il y a des tuto d'un peu de tout.
