### ISSUE TITLE
Bug trouvé à l'utilisation

### ISSUE THREAD

**Issue by NouRs0n** [toulousain79/MySB#17]
Bug rencontré
-lien vers cakebox page UserInfo.
-Accès page de log et d'autres URL depuis la page UserInfo (Partie MainUser) oblige de retaper le password.
-Seedbox Manager ne conserve aucun réglage (Choix du thème/ajout de raccourci dans la barre du haut/ choix de la partition à surveiller)

Suggestion
IRSSI ou ZNC (bouncer IRC)
[YoutubeDL] (https://github.com/rg3/youtube-dl) (avec [webUI] (https://github.com/p1rox/Youtube-dl-WebUI))
Dans la section Renting Infos avoir le résultat (dernière ligne) à 2chiffre après la virgule.

**Comment by toulousain79** [comment]
-lien vers cakebox page UserInfo
--> Corrigé

-Accès page de log et d'autres URL depuis la page UserInfo (Partie MainUser) oblige de retaper le password.
--> Il s'agit de l'authentification gérée par WolfCMS. Si je la désactive, tous les users connaissant l'URL pourront accéder à toutes les pages dédiées à l'utilisateur principal.

-Seedbox Manager ne conserve aucun réglage (Choix du thème/ajout de raccourci dans la barre du haut/ choix de la partition à surveiller)
--> Corrigé

IRSSI ou ZNC (bouncer IRC)
--> je pense intégrer IRSSI dans une prochaine version.

YoutubeDL (avec webUI)
--> bonne idée, à prévoir dans une prochaine version

Dans la section Renting Infos avoir le résultat (dernière ligne) à 2chiffre après la virgule.
--> actuellement les dizaines de décimale ne sont pas afficher car le montant est arrondi vers l'entier le proche (7,2 = 7 ou 8,6 = 9), à prévoir dans la prochaine version

pour appliquer les quelques corrections, tu peux exécuter 'MySB_GitHubRepoUpdate'. ensuite tu pourras effectuer tes modifications dans SM et la configuration restera.

merci pour ton retour ;-)

**Comment by NouRs0n** [comment]
Génial, merci de ta réactivité ! je suis ravis que les suggestions t'apportent des idées :)

Je comprend pour l'idée de retaper le mots de passe, mais on en a pas besoin quand on passe par le menu du haut pour accéder aux log, ça devrait le demander partout, du coups, non?

Avec plaisir pour le retour je pense que c'est l'essentiel pour qu'un projet avance.

**Comment by toulousain79** [comment]
Tu as donc un comportement du portail que je ne connais pas. Normalement, que tu cliques sur un des liens (main user) dans la page User Infos, ou ceux présent dans le menu principal, c'est la même chose.
Quelle est la méthode d'authentification que tu as? Popup géré par le navigateur, ou une page avec une option "Remember me for 30 minutes" ?

**Comment by NouRs0n** [comment]
Autant pour moi, c'est moi qui avait mal calculer. Je viens de refaire l'essaie avec mes 2~3 ordis, c’était surement parce que je m’était identifier plus tôt que c'était passer direct, car là il me demande bien le mot de passe depuis un autre ordi. 

Donc autant pour moi, c'est ma faute

**Comment by toulousain79** [comment]
Pas de soucis

**Comment by NouRs0n** [comment]
J'y repense maintenant, non pas un bug... enfin je pense pas. Mais en voulant modifier (en SSH) la page d'index de MySB je me suis rendu compte que les accents mettaient le bronx, je ne sais pas si c'est qu'une question de codage, mais voila c'est dit :)

**Comment by toulousain79** [comment]
Que veux-tu dire par 'mettaient le bronx' ?
Si tu utilises SSH, pense à changer le 'character set' de Putty (ou autre) en utilisant UTF-8.
Aussi, penses-tu à remplacer les caractères spéciaux dans la page HTML (http://www.frinux.fr/projects/js_converthtml/) ?

Mais attention, le script 'MySB_GitHubRepoUpdate' est exécuté tous les 2 jours. Cela signifie que toutes modifications effectuées sur les fichiers présents dans l'arborescence de /etc/MySB seront mis à jour (écrasés par ceux présents sur GitHub).

**Comment by NouRs0n** [comment]
Bonjour et désolé je n'avais pas vu votre/ta réponse.
Pour Putty les accents sont bien gérer, c'est une fois le *.php modifier et nginx recharger que la page *.php (en ligne) reste blanche il n'y a plus de texte, uniquement le CMS (fond, en tête, bas de page)

Alors non, je ne savais pas qu'on devait remplacer les caractères spéciaux dans la page HTML je vais m'en servir de référence, je t'en remercie.

Et oui en effet c'est d'ailleurs pour cela que mes paramètres de seedbox manager ne restai pas, il recharge l'ensemble du script tous les 2 jours

Merci de tes reponses

**Comment by toulousain79** [comment]
La page blanche peut provenir soit d'une erreur de syntaxe dans la page soit de droits du fichier PHP. Ça arrive en éditant en root.
Sinon je travail sur la gestion du français anglais dans la v2.2. Il sera possible de choisir la langue dans les options.

**Comment by NouRs0n** [comment]
Hello et pardon j'ai eut une semaine assez délicate.
Bref, en fait j'ai voulu commencer à éditer/modifier en essayant de le faire sur GitHub, mais ne comprenant pas grand chose je mettais dis que via le SSH sa serai "une bonne idée".... pour au final me rendre compte que le plus simple serai de DL le dépôt en ZIP et de modifier les .php avec notepad++ ^^

Désolé de ces dérangements, je vais finir par apporter une aide :p

**Comment by toulousain79** [comment]
Salut, pour éditer via GutHub et en utilisant ton compte, il suffit d'installer le client Windows. A partir de là tu peux éditer les fichiers en local sur ton ordi. Ensuite tu pourras mettre à jour ton dépôt.
