### ISSUE TITLE
Feature requests (autodl-irssi, zoho email, instant setup)

### ISSUE THREAD

**Issue by rolltidehero** [toulousain79/MySB#19]
Thanks so much for the script! I know this isn't an issue but I didn't know where else to ask. Will you be adding autodl-irssi support for this or providing a guide on how to set it up for multi-users? Also, how do I change the name on the email that is sent when users are created from MySB to my actual name? 

I think some great additions would be (ordered by importance):
1. autodl-irssi support with automatic configuration when user is created (everyone uses it)
2. The ability to create user with one command. Example: "MySB_CreateUser username email" (gives ability for seedbox hosts to offer instant setup)
3. Zoho Email Support to go along with OVH, Yahoo and Gmail. (Very popular, free email hosting)

Thanks again!

**Comment by toulousain79** [comment]
Hi,

Thank you for your comments.
I take into consideration your proposals. I'll see to integrate them in a future release.

1 / AutoDL-irssi will be part of a future release
2 / With the portal, you can create a user in one step. Can you explain in more detail what you want exactly ?
3 / For Zoho Mail, I will seek the technical details to imagine integration (SMTP server, port, SSL or TLS, ...).

I am currently working on v2.2 that integrates the ability to switch the language (French/English). I also integrates Pydio. I haven't made much progress in recent weeks. I wish I could get back quickly.

Thank you for your support.

**Comment by rolltidehero** [comment]
1. AutoDL-irssi is most important but..

2. The way I had my previous setup was when a user made a purchase on my WHMCS web server, it would remote into the seedbox server and run a SSH command. This automatically created the users account when payment was received.

3. Outgoing Server Name: smtp.zoho.com
Port: 465
Security Type: SSL 
Require Authentication: Yes.

**Comment by fiosaddict** [comment]
I 2nd the AutoDL-irssi community edition as well. Thank you SO much for writing this script. If you are willing to work on this and polish it, include Deluged and deluge-console and have the user running the script choose the username and password for the Deluge Thin-client. Flexget installation would be helpful for Deluge for those nice trackers that only allows RSS notification feeds. Lastly, how about a full Xfce installation, and everything else, so we can use the X2go client to connect to our server's desktop which makes a ton of things easier to do right from the start. I understand you have a real life and there's a lot of work to be done. However, I *totally* willing to send you a *very* significant donation for all your hard work and dedication to the project. (I'm not talking about $10 either.........just a few more things like I said, and hopefully immaculate English translation for absolutely every page and I'll keep an entire  bitcoin on my list for you for Christmas :100:

**Comment by toulousain79** [comment]
Wow, I just read your message, I had not seen ...
I am attentive to all that can asked myself. All ideas and proposals are interesting and relevant, but if I integrate all these functions, MySB could become much more complex and less easy to use.
MySB became an important project that requires more and more time, I have not.
Each version takes me several weeks to several months by working nights and weekends, in addition to my work day. This rhythm is that difficult to hold, it's tiring.
I finish v3.4, if I can continue to evolve MySB, I will select the new features depending on the complexity of added tools.
I'm not looking for large donations promises. I prefer to benefit small donations, possibly recurring, but real, for an existing project.
You can even find a "Donate" button at the bottom of each page of the portal MySB.
