### ISSUE TITLE
chown issue when creating from SSH

### ISSUE THREAD

**Issue by rolltidehero** [toulousain79/MySB#20]
When I create users from SSH, it shows that the owner of the /home/user33/rutorrent/torrents folder is root, so all disk quota is assigned to root instead of the user. This was fixed by changing ownership of the torrents folder.

Note: It works correctly when adding users from the GUI. This only happens when adding users via SSH using MySB_CreateUser

**Comment by toulousain79** [comment]
Hi, thanks for your feedback.

The GUI use exactly the same command than SSH. It is the script Apply con fig.big that is executed. I will check when I will have the time.

Regards
