### ISSUE TITLE
Thank You and a Feature Request

### ISSUE THREAD

**Issue by RXWatcher1** [toulousain79/MySB#21]
First Off..Thank You! I've been looking through the code and its obvious you spent a lot of time on it. Esp how the firewall rules work.

This brings me to my post. I've been struggling with how to keep firewall rules. They seem to get wiped out all the time. I've added some services to my server (Syncthing is the main one) and wish to open ports for it's web GUI.  My request is that you add a file somewhere that would allow us to open custom inbound and outbound ports for our registered users and then another file to open inbound and outbound ports for all. This should allow us to control the firewall enough to open ports for added services.

Again..thank you for the effort...it is appreciated by me.

**Comment by toulousain79** [comment]
Thank you very much ;-)
Yes, I spent a lot of time.
Currently, port services are found in the database. For the next version, I want to migrate SQLite to MySQL. So if you're patient, I may consider adding a page on the portal for the primary user. This page could afford to add ports to open for IPtables and PeerGuardian. It is a good idea.
For now I finish the integration of ownCloud.

Regards
