### ISSUE TITLE
Yo, what's up?

### ISSUE THREAD

**Issue by ItsAdventureTime** [toulousain79/MySB#22]
Hey,

I was checking your awesome script, honestly I totally forgot about it because the only thing that comes into my mind was the "Kerwood Seedbox Script". Good thing that I saw your script again! It has everything that I need. My main concern is the "Seedbox Manager". What does it usually do? I can help you out so that it will have an "English" version.

I am not using OVH anymore. I have a new provider. They are soooo fast and worth it!

As for the documentation, I was thinking that you should have a section where it shows that your script is installing in the user's server and a brief explanation of the function and the purpose.

By the way, I like your script. It is really user-friendly.
Have you tried to use other operating systems too?

Thanks.

**Comment by toulousain79** [comment]
Hello,

Sorry for being slow to respond, much work ...

"Seedbox Manager" is developed by "[Magicalex](https://github.com/Magicalex/seedbox-manager)". If you want support for English, I think it is to him that you should ask.
The features are:
- Links to ruTorrent and Cakebox in the navbar, this feature is also present in the portal MySB (menu Services)
- Reminder of the FTP and SFTP ids of the user, this feature is also present in the MySB portal in the Information page of the user
- A support module with ticket, I admit to not know how it works ...
- Server Statistics also feature added to MySB with loadavg
- User information (disk space, visitor IP address)
- A tool to generate configuration files and filezilla Transdroid for MySB, I think this is the most interesting part. You can download FileZilla and Transdroid configuration files.

In summary, Seedbox-Manager is not essential if you installed MySB. I think the most interesting and the function to download the configuration files for FileZilla and TansDroid.

For documentation, I'm not sure what you ask. You would see a page listing all installed packages? If this is the case, it seem complicated to me given the importance of the project. There have far too much to describe.

For documentation, I'm not sure what you ask. You would see a page listing all installed packages? If this is the case, it seem complicated to me given the importance of the project. There have far too much to describe.

By cons, I can certainly describe quickly the value of the various services included in MySB (PeerGuardian, DNScrypt-proxy ...). Do you speak of this type of information?

For now, only Debian 7 is supported. I would maybe change 8. But only for Debian, not Ubuntu, CentOS not.
