### ISSUE TITLE
The use of domain name, is it possible?

### ISSUE THREAD

**Issue by ItsAdventureTime** [toulousain79/MySB#23]
Hello,

I was thinking of using a domain name is better than memorizing the IP address of my seedbox which in my opinion, is safer.

For example, the seedbox is https://x.x.x.x/rutorrent or http://x.x.x.x/rutorrent right?

Can I use seedbox.com and not seedbox.com/rutorrent ? or even seedbox.domain.com and not seedbox.domain.com/rutorrent ?

I think this has something to do with .htaccess but the script is using nginx not Apache. In my opinion, of course, nginx is faster than Apache :+1: 

Thanks.

**Comment by toulousain79** [comment]
You can choose a custom domain name. It's already managed during installation. By default, the actual name of your server will be detected (eg ovhXXXX.ovh.com). But you can enter a different question when you will be asked.

The services will be accessible via the following addresses:
- https://myserver.mydomain.com:8889/ _for MySB portal_
- https://myserver.mydomain.com:8889/ru _for ruTorrent_
- https://myserver.mydomain.com:8889/cb _for Cakebox_
- https://myserver.mydomain.com:8889/owncloud _for ownCloud_
- https://myserver.mydomain.com:8889/loadavg/public/ _for loadavg (statistics)_

For now, it is the only unique way to access services.
You could make changes manually on your server, but it will not be supported for the support. And most important, it will cause problems if you installed the updates to MySB.

Bye
