### ISSUE TITLE
file permission

### ISSUE THREAD

**Issue by geroboame66** [toulousain79/MySB#25]
hello;

I have moved file on rtorrent/completed to folder on owncloud , but nothing apear on owncloud ....
How to set the permission for files/folder on owncloud ?

**Comment by toulousain79** [comment]
Hi,
With v3.3, scan will be perform after a download. ownCloud refresh files with client or with web interface. If you add a files by command line or by FTP, ownCloud will not see the new files.
By command line, you can perform a uniq scan like that (v3.3):

bash /opt/MySB/scripts/ownCloud.bsh scan username

OR

If you have v3.2 you can do this:

source /optMySB/inc/vars
su -s /bin/sh www-data -c "/usr/bin/php $ownCloudDir/occ files:scan --all"

bye
