### ISSUE TITLE
MySB Main Admin Portal Links Issue

### ISSUE THREAD

**Issue by betaboy44** [toulousain79/MySB#26]
Hello,

In MySB main admin portal the links are faulty, all links are opening as "https://localhost:1234", but they should open as "https://11.11.11.11:1234", but inspite of server ip, links are opening as name localhost so every link is opening as dead, i have to replace each opening link localhost word by ip in address bar.

Regards

**Comment by betaboy44** [comment]
Moreover kindly tell me how to remove IP restriction feature from this great seedbox ?
I have dynamic ip and i do not want to use services such as Dyndns or no-ip,..i simply want to open my seedbox from any ip i want.

Regards

**Comment by toulousain79** [comment]
Hi,
I have the impression that you started the installation of MySB via a direct console and not remotely by SSH.
When installing MySB, it is required to confirm the IP address of the server. You must confirm the public IP address of the server.

The IP restriction has nothing to do with the address of the links. All links are generated on the fly according to the public IP address of the server specified during the installation (questions list on first step).

You can disable the IP restriction via the portal:
Main user > System Options > IP restriction

Let me know your situation.

Regards,
