### ISSUE TITLE
Error on install:

### ISSUE THREAD

**Issue by Kongledyret** [toulousain79/MySB#27]
Hi!
Thanks for the script!

I've experiencing issues on install. Setup is going good until:

"12/38     - Generating the NginX Certificate with Let's Encrypt.........................................................................................."

On this is just freezes and ssh gets unresponsive. 

Any idea?

**Comment by toulousain79** [comment]
Hi,
Which version did you install ?
Did you install MySB on a virtual server?

You can connect to your server by SSH with the new port.
You have started to install MySB with the port 22, but during installation, the port change to 8192 (if you did'nt change it during questions).
You can get logs installation available in /opt/MySB/logs/LetsEncrypt.log.
Can you give me this content ?

**Comment by Kongledyret** [comment]
Fixed it. Domain was not properly forwarded to server IP.
