### ISSUE TITLE
Redirections

### ISSUE THREAD

**Issue by Setsuneh** [toulousain79/MySB#29]
Hi,

Thanks for this script. However is it normal to have this type of url for exemple to Management, or LoadAVG etc ...? 

"https://seedbox:8189/?/repVYhmFbf0F1Nsnci7B_d70gU6vhGM9/login/login" and there is no redirection with the real IP..

**Comment by toulousain79** [comment]
Hi,

It seems that you are installed MySB on a server with a local IP address and not on a dedicated server with a public IP address.

You need to use a service like No-IP or DynDNS to create a FQDN name (eg seedbox.dyndns.org) and fill in your public IP address which will be linked to seedbox.dyndns.org.
Then, if your router allows it, you have to add your non FQDN (ex: seedbox.dyndns.org) and force the actual local IP address of your server.

Then you can install MySB and use all services normally.
During the installation of MySB, you will need to enter "seedbox.dyndns.org" for the question "What is the hostname of your server (Fully Qualified Domain Name)?"

FQDN = Fully Qualified Domain Name

https://seedbox.dyndns.org:8189/ru (ruTorrrent)
https://seedbox.dyndns.org:8189/sm (Seedbox-Manager)
https://seedbox.dyndns.org:8189/cb (Cakebox)
https://seedbox.dyndns.org:8189/la/public/ (LoadAvg)
...

![router](https://user-images.githubusercontent.com/7481084/38633898-4b0c8f08-3dc1-11e8-9a31-dab3d1b2e644.jpg)

Keep me informed.
