### ISSUE TITLE
Using MySB was not successful.

### ISSUE THREAD

**Issue by ItsAdventureTime** [toulousain79/MySB#3]
Hi,

First of all, I would like to congratulate you with the script! I find your script awesome and full of really nice and unique features! This is definitely better than Kerwood and the SeedboxCreatorScript. Although, I would like to be able to use CentOS instead of Debian/Ubuntu though. Anyway, I installed it on my Kimsufi server, I used Debian 7. Well, after the installation, it automatically restarted and then nothing happens. I was shocked because OVH sent me an e-mail that says my server has an issue and needs to be checked by their technicians. I tried doing a cold reboot yet I can only boot into the rescue mode. Also, it seems the hostname (FQDN) is wrong. For example, I can see ns1234567.ip-1-234-567.eu which does not allow me to access anything. I believe it should be the IP address of the server, right? Another thing, I noticed that while your script is configuring ruTorrent and the plugins, it took more than 20 minutes just to finish it. When I used Ubuntu 14.x (the latest release), well everything was fast. Although, I am receiving an e-mail from OVH about the intervention thing again. It seems that they cannot ping my server anymore that is why their system is probably thinking that my server is broken. Which is weird, because every time your script finished the installation, it automatically shutdown or restarts my server wherein it does not boot anymore.

Thanks.

**Comment by toulousain79** [comment]
Without log file or access to your server, I can not help you much.
I can only advise you to wait a little, until I finish the new version.

Regards

**Comment by ItsAdventureTime** [comment]
Hi,

Thanks. Well, for the log files they are now gone. Because I reformatted it and installed Ubuntu Server 14.10. I must say, the performance of your script is much faster than Debian 7 and I don’t know why. Another thing, I hope you can create a version of your script for CentOS. Also, what are the enabled “jails” in the included fail2ban of your script?

Thanks.

**Comment by ItsAdventureTime** [comment]
Hi, 


Your script does not work on Ubuntu Server v14.10 because after your script restarted it, the server does not work anymore and I have not received an e-mail that contains my logins. In short, it is only for Debian 7. 




Thanks. 


—

**Comment by ItsAdventureTime** [comment]
I am currently installing your script into a Debian 7 server again. The installation is really slow yet it works. After your script restarts my server (although it takes a long time), I receive the e-mail that contains my login info.

![screen shot 2015-01-10 at 7 08 36 am](https://cloud.githubusercontent.com/assets/8077729/5688878/9f7b5092-9897-11e4-821f-c28fb79b8b46.png)

**Comment by toulousain79** [comment]
Well, thank you for your report.
Sources.list are not configured for Ubuntu but only for Debian, for now.
Did you use LOCAL or another SMTP provider?

For Fail2ban, you can check rules here https://github.com/toulousain79/MySB/blob/v1.1/install/Fail2Ban. All users' IP are in the whitlist (ignoreip). All new IP are added here.

**Comment by ItsAdventureTime** [comment]
Hi,

Thanks for replying. It's a pleasure to report those things to you! As
always, I use LOCAL instead of manually using an SMTP server. I just use my
GMail e-mail as the address where your script is going to send my login
info. Awesome! Thank you for providing me the fail2ban stuff.

I am willing to let you have access to my server. Actually, it's an old
one. I won't be renewing it by next month because I was able to buy a much
more better server than that one. So I am just using the old server (where
I am using your script) like a test server to check which operating system
your script is compatible.

Another thing, for the whitlist IP thing, my ISP provides me dynamic IPs.

Thanks.

**Comment by toulousain79** [comment]
For a dynamic IP address, the next version will be able to handle this.
https://github.com/toulousain79/MySB/blob/dev/Changelog.md
The script 'https://github.com/toulousain79/MySB/blob/dev/scripts/DynamicAddressResolver.bsh' will be run every 5 minutes to update the IPs.
For the primary user at the beginning of the installation, you must enter your IP directly.
After installation, you have to go in the portal 'User> Manage Addresses' and add a host name instead (or in addition) of existing addresses. To use a host name, you must have an account with No-IP or DynDNS (or other).

**Comment by ItsAdventureTime** [comment]
I am willing to give you access to my server for debugging the script. I'll send you the details in private email

—

**Comment by ItsAdventureTime** [comment]
I have a question.
When your script reaches the end and wants to restart the server of the user of your script, what is the command that you use? Do you use "shutdown -r now"?

**Comment by toulousain79** [comment]
No, reboot

**Comment by ItsAdventureTime** [comment]
So, you use “reboot now” ?
I will be sending you screenshots of what happened to my server. By the 
way, using an Ubuntu-based operating  system doesn’t work. The second 
“screen” session just crashes. It is the same thing when using Debian 6. 
In short, since you have mentioned that it works when using Debian 7, it 
really does work. Lol.

From:  toulousain79 <notifications@github.com>
Reply-To:  toulousain79/MySB 
<reply+007b41a1f3c6e9c9aeadc7e361344054913de64ddd76065c92cf0000000110d4fe0c
92a169ce03352411@reply.github.com>
Date:  Tuesday, January 20, 2015 at 1:17 AM
To:  toulousain79/MySB <MySB@noreply.github.com>
Cc:  Juan Karlo de Guzman <jkarlodg@gmail.com>
Subject:  Re: [MySB] Using MySB was not successful. (#3)


No, reboot

**Comment by toulousain79** [comment]
I'm almost finished the new version.
In it, I disabled the possibility to install MySB on Ubuntu or Debian < 7.
I am actually interested to have screenshots, it would help to development.

**Comment by ItsAdventureTime** [comment]
Of course, I’d be happy to provide you the screenshots. Basically, it 
happens every time the installation finishes. I have no idea why. I find 
it really disappointing though. Because I really want to use your script.


From:  toulousain79 <notifications@github.com>
Reply-To:  toulousain79/MySB 
<reply+007b41a18d7b6d68e837ef446fbf6d174ae09c11234a16a692cf0000000110d50070
92a169ce03352411@reply.github.com>
Date:  Tuesday, January 20, 2015 at 1:27 AM
To:  toulousain79/MySB <MySB@noreply.github.com>
Cc:  Juan Karlo de Guzman <jkarlodg@gmail.com>
Subject:  Re: [MySB] Using MySB was not successful. (#3)


I'm almost finished the new version.
In it, I disabled the possibility to install MySB on Ubuntu or Debian < 7.
I am actually interested to have screenshots, it would help to development.

**Comment by toulousain79** [comment]
Where do you want to install MySB, at home or a provider ?

**Comment by ItsAdventureTime** [comment]
I rent a dedicated server in France.

From:  toulousain79 <notifications@github.com>
Reply-To:  toulousain79/MySB 
<reply+007b41a16269bc68a29134f236c41c9ad88724ada98b689692cf0000000110d50390
92a169ce03352411@reply.github.com>
Date:  Tuesday, January 20, 2015 at 1:40 AM
To:  toulousain79/MySB <MySB@noreply.github.com>
Cc:  Juan Karlo de Guzman <jkarlodg@gmail.com>
Subject:  Re: [MySB] Using MySB was not successful. (#3)


Where do you want to install MySB, at home or a provider ?

**Comment by toulousain79** [comment]
Do you have the opportunity to try the development version, and make me a return?

When this version is no longer being developed, it will surely be necessary to reinstall it.

https://github.com/toulousain79/MySB/tree/dev

Thank you very much for your participation.

**Comment by ItsAdventureTime** [comment]
I've tried it.
Here's the result:

```
Distributor ID	: Debian
Linux

server
hostname
eth0
eth0
Architecture	: 64
root@********:~# 
```

I installed it under Debian 7.

**Comment by toulousain79** [comment]
What is your server model and kernel??? I have tested it on Debian 7 32 and 64 and it was ok. Tested it too on Ubuntu, the script say was not possible. But I never had this display...

**Comment by ItsAdventureTime** [comment]
Tell me your e-mail and I will let you use my server. 

—

**Comment by toulousain79** [comment]
toulousain79@gmail.com

**Comment by toulousain79** [comment]
Can you test again please ? I think I found the mistake.

**Comment by ItsAdventureTime** [comment]
Okay wait up let me reinstall debian 7

—

**Comment by ItsAdventureTime** [comment]
Please check your e-mail. I just sent the required info. 

—
