### ISSUE TITLE
Problème avec adresse mail et samba

### ISSUE THREAD

**Issue by dmckminard** [toulousain79/MySB#33]
Bonjour !

J'espère que ça ne te déranges pas que j'écrive ceci en français, sinon je peux traduire sans soucis.
J'ai un soucis concernant l'adresse mail : en effet, à la création du serveur et à la création d'un nouvel utilisateur, je ne reçois pas de mail (même dans les spams). J'ai essayé plusieurs fois avec gmail et yahoo. 

De plus, je ne comprends pas bien la commande pour monter le partage de fichier samba. Quand je l'exécute, il m'indique : 

> mount: mauvais type de système de fichiers, option erronée, superbloc erroné
>         sur -, page de code ou programme auxiliaire manquant, ou autre erreur
>         (pour plusieurs système de fichiers (NFS ou CIFS par exemple), un
>         programme /sbin/mount.<type> auxiliaire pourrait être nécessaire)

Sais- tu d'où cela peut venir ?
En tout cas super projet, bravo à toi, le reste fonctionne à merveille !

**Comment by dmckminard** [comment]
Petit up, désolé je suis débutant en la matière... 
La seedbox est installé sur mon serveur debian, et je suis sur mac. Je souhaiterais pouvoir bénéficier des sauvegardes Time Machine sur mon mac, en passant par Samba (donc par la seedbox).
J'avais rentré la commande indiquée plus haut sur mon serveur, et non dans le terminal de mon mac (ça commence bien)
Mais je ne comprends pas bien cette commande et comment l'utiliser, il faut j'imagine que je soit connecté à un de mes fichiers de conf OpenVpn, mais lequel ? TUN ? TAP ? WithoutGW ?
Et ensuite, il serait possible d'avoir plus d'infos sur cette commande, et plus précisément pour le répertoire à monter ? 

> mount - <mount_dir> -t cifs -o noatime,nodiratime,UNC=//10.0.x.1/<User>,username=<User>,password=<Password>

**Comment by toulousain79** [comment]
Salut,

Le français me va bien ;-)

Si tu es d'accord, nous prendrons un peu de temps pour regarder cela ensemble dans la semaine ou ce weekend.
Je te contacte rapidement.

Merci ;-)

**Comment by dmckminard** [comment]
Salut !

D’accord, c’est super, merci beaucoup de pouvoir m’accorder ce temps ! 
À très bientôt,
David

**Comment by toulousain79** [comment]
Salut

Envoie un mail à toulousain79-chez-gmail.com
Cela permettra de discuter un peu librement.

Peux-tu déjà me donner des infos sur ton serveur ? Quel est ton hébergeur par exemple ?
