### ISSUE TITLE
Configurer Plex

### ISSUE THREAD

**Issue by ghost** [toulousain79/MySB#34]
Bonjour merci pour ce magnifique script

Fraichement installé sur un serveur dédié tout marche correctement avec tout les options, je voudrais utilisé plex maintenant comment faire ?

**Comment by toulousain79** [comment]
Bonjour

Merci ;-)

Ouvre ton navigateur et assures-toi d'être déconnecté de ton compte Plex.
Ouvre le portail MySB, et rends toi sur "Services > Plex Media Server".

Comme je l'ai fait pour certaines personnes, je peux te le configurer si tu le souhaites par TeamViewer.

Tiens moi au jus ;-)

**Comment by ghost** [comment]
Bonjour

cela ne marche pas je me suis deconecté via plex.tv et mon liens et me reconnecté et toujours "Aucun serveur trouvé. Installez Plex Media Server et celui-ci apparaîtra ici."

**Comment by toulousain79** [comment]
toulousain79 at gmail


Le sam. 14 juil. 2018 à 19:43, Darkspace <notifications@github.com> a
écrit :
