### ISSUE TITLE
suivi du projet impossible

### ISSUE THREAD

**Issue by s-kocher** [toulousain79/MySB#35]
Bonjour, ce n'est pas vraiment une feature request mais plus une question indiscrète ;)

Pourquoi seuls les derniers commits sont-ils conservés et qu'on ne peut donc pas suivre toutes les modifications apportées au projet ?
- 9 commits sur la branche 5.2 avec en grande majorité des commentaires génériques "5.2"
- 8 commits sur la v99.99 remontant à il y a 2 heures  maximum avec des commentaires génériques

Cela rend impossible le suivi du projet qui est très intéressant et unique dans le monde des seedbox sur serveur dédié, surtout pour ceux amateurs de sécurité se souciant de la fréquence des updates des différents composants ou optimisation de la configuration / scripts de déploiement / ...

**Comment by toulousain79** [comment]
Bonjour,

J'avoue que je suis surpris de cette remarque...
J'ai gardé une veille habitude que de purger tout l'historique des commits où je pouvais trouver parfois des données sensibles par oubli dans le code...

Aussi, les modifications importantes sont ajoutées dans le Changelog.
En 4 ans, tu es le premier à me faire la remarque.
Je tâcherai de laisser l'historique pour les prochaines versions, pour mon fan club ;-)

**Comment by s-kocher** [comment]
ok merci pour les explications :)

En cas de bourde avec données sensibles commitées par erreur, il y a a toujours la possibilité de faire un git filter-branch ou d'utiliser le très efficace git bfg juste pour retirer de l'historique des commits le contenu sensible, de la à tout supprimer au cas où, il y a un monde ;) 
C'est, il me semble pas trop dans la philosophie d'un outil de gestion de versions de supprimer les versions et donc de cleaner les commit, en témoigne le repo de l'inventeur de git Torvald himself et le repo linux : https://github.com/torvalds/linux et ses presque 800.00 commits :)
