### ISSUE TITLE
doesn't work for me

### ISSUE THREAD

**Issue by triggz** [toulousain79/MySB#5]
everything seems to work fine until it starts the screen session and asks me if i want to continue with the install, i input yes and it says 

#### Preparing the installation ####
1/22      - Creating security rules....Write failed: Connection reset by peer

then it disconnects me from the server and I am unable to gain access again without reinstalling debian

I've tried reinstalling the script around 15 times choosing different features and settings to install, always with the same result. Here is the latest install settings I used, I tried to install the bare minimum.

1) Have you confirmed your IP (yours, not the server) YES

2) Did you use an external SMTP server ? If so which one? Have you received the confirmation email before restarting ? NO and no I never received any emails

3) What time zone scripting offered you ? Which one have you approved ? It offers Europe/Paris, for this particular install I kept it as Europe/Paris (although this is confusing maybe it would be a good idea to use UTC or something?) 

4) Which network interface script offered you ? Which one have you approved ? It offers my servers IP address, maybe this is where it is going wrong? I approved my servers IP address this time but I have used both examples eth0 and nic0 before with the same results.

5) Does the IP address of the server was correct ? Have you change it ? YES and NO 

6) What hostname script give to you ? Have you change it ? triggz and NO

7) Have you changed any of the ports offered ? (HTTP, HTTPS, SSH, ...) NO

8) Have you installed Seedbox-Manager ? NO

9) Have you installed Cakebox ? NO

10) Have you installed Webmin ? NO

11) Have you installed OpenVPN ? NO

12) Have you installed PeerGuardian ? NO

13) Have you installed DNScrypt ? NO

PS I'm very new to Linux, I apologize if it's something I'm doing wrong. I hope we can sort this, your seedbox script is by far the best I have found.

**Comment by toulousain79** [comment]
Hi,
I suppose you have an OVH server (or kimsufi SoYouStart), right?
Before you start installing MySB, what is the result of the following command ?
uname -a

**Comment by triggz** [comment]
I have an AlphaRacks server this is the output of the commandLinux triggz 2.6.32-042stab102.9 #1 SMP Fri Dec 19 20:34:40 MSK 2014 i686 GNU/Linux

Date: Mon, 16 Feb 2015 09:41:24 -0800

**Comment by toulousain79** [comment]
OK, you do not have a Debian kernel.
What is your AlphaRacks server model ? (Budget VPS OVZ-X or Dedicated Server)
Try running the command 'aptitude search linux-image', and give me the result.

**Comment by triggz** [comment]
Budget VPS OVZ-X i'm guessing, I got the 2015 New Year Special - Los Angeles OVZ 4GB 

I get a command not found error

**Comment by toulousain79** [comment]
I'm sorry but MySB is not compatible with VPS.
MySB use some tools that require a standard kernel, and VPS does not use standard kernel.
If you want to use MySB, you must get a real dedicated server, not a Virtual Private Server.

**Comment by triggz** [comment]
ok thanks anyway
