### ISSUE TITLE
Installation bloquée étape 14

### ISSUE THREAD

**Issue by Matthi3u** [toulousain79/MySB#51]
Bonjour, merci pour script mais mon installation de celui-ci est bloqué depuis plus de 5h sur l'étape 14 création des certificats let's Encrypt, je ne sais plus exactement le titre parce qu'il y a tellement eu de pointillé.

Mon serveur ne respect pas les recommandation, c'est un KS-3 de Kimsufi, mais je n'ai pas coché l'option Plex, je n'ai mis que le nécessaire je veut l'utiliser juste en seedbox, pas de fioriture.

Je n'ai trouvé aucun log parlant d'erreur, le seul fichier qui est mis à jour c'est le /tmp/cpu_stats assez fréquemment et le /run/motd.dunamic qui c'est mis à jour à 16h15 sinon rien depuis 12h.

Es-ce normal ?

Merci d'avance de ta réponse

Matthi3u

**Comment by Matthi3u** [comment]
Au cas où mes logs
[logs.zip](https://github.com/toulousain79/MySB/files/2760310/logs.zip)

**Comment by Matthi3u** [comment]
voici le log de l'installation de Let's Encrypt 
[LetsEncrypt.log](https://github.com/toulousain79/MySB/files/2760359/LetsEncrypt.log)

**Comment by Matthi3u** [comment]
J'ai réussi à me débrouiller, ça à bloqué à l'installation des packages suivants :
python3-pkg-resources python3-virtualenv virtualenv 
J'ai lancé à la main et c'est bon après un MySBClean

Peut-être vérifier le script à ce moment.

Bonne soirée.

**Comment by g0tama** [comment]
Même chose pour moi, bloqué sur l'étape d'installation Let's Encrypt.
J'ai essayé l'installation de python mais impossible de reprendre l'installation en cours ou de faire un MySBClean (la commande n'est pas disponible).
Je restaure et j'essaye sur Debian 8.4 pour voir...

**Comment by Matthi3u** [comment]
c'est ce script : 
/opt/MySB/install/MySB_CleanAll.bsh

**Comment by toulousain79** [comment]
Hello
Je viens seulement de prendre connaissance de vos messages...
Il semble que je n'ai pas reçu les notifications provenant de GitHub !

Pour répondre à vos posts, ce bug a été corrigé depuis en forçant l'installation des paquets Python nécessaires par le script certbot-auto _(Let's Encrypt)_. Car c'est ce dernier qui préparent l'environnement pour l'obtention du certificat.

A l'avenir, si jamais vous ne voyez pas de réponse de ma part, essayez sur [Discord](https://github.com/toulousain79/MySB/wiki/%5BHelp%5D-Support).
Je suis assez réactif et disponible _(quand je vois les messages)_.
