### ISSUE TITLE
Problème mise à jour MySB

### ISSUE THREAD

**Issue by CaptainTib** [toulousain79/MySB#6]
Bonjour,

J'avais une installation de MySB v1.1 relativement light (pas de OpenVPN, Webmin, PlexMedia Server)
mais l'ensemble fonctionnait relativement bien. (Juste un problème de file-manager sur rutorrent)

Depuis hier, j'ai fait un test de mise à jour avec la commande qui convient et la, j'ai plusieurs soucis.

Le premier est sur rtorrent qui ne marche plus du tout. (ci -joint le code dans la console rutorrent http://pastebin.com/nDgnHrdP )
Le deuxième est sur OpenVPN. J'ai installé via la mise à jour OpenVPN mais je n'ai absolument aucun fichier de configuration de créé.

Pour l'installation de la V1.1, j'avais suivi les recommandations pour la V2 qui était encore dans la branche dev à savoir l'utilisation du kernel par défaut.
J'avais eu un soucis pour seedbox manager, la compilation de la fonction de reboot ne marchait pas, j'ai du récupérer à la main la dernière version sur le git de l'auteur, je n'ai jamais su d'où l'erreur venait.. (plusieurs tentatives d'installation avaient été faite).

Je me tiens à votre disposition pour l'envoi de log, pour d'eventuels tests et autres manipulations a faire.

Thibault

**Comment by toulousain79** [comment]
Bonjour,
Actuellement vous disposez bien de la v2.0 et non de la dev ?
1/ Supprimez le fichier '/etc/MySB/web/rutorrent/share/users/USER/settings/autotools.dat'
2/ Exécuter la commande 'MySB_GitHubRepoUpdate'.
3/ Pour OpenVPN, je n'ai pas prévu le coup d'une installation du service pendant une mise à jour...
Il faut créer vos fichiers de configuration à l'aide de cette commande:

/bin/bash /etc/MySB/install/OpenVPN client "VOTRE_USERNAME" "INSTALL"

NOTE: Cela va créer vos configurations en silence.

4/ Réinitialisez votre mot de passe (ligne de commande ou via le portail), vous pouvez utiliser le même mot de passe. Cela va zipper vos fichiers de config OpenVPN et le rendre téléchargeable via le portail.

Tenez-moi informé.
Si vous le pouvez, je serais preneur de l'ensemble de vos fichiers de logs présents dans '/etc/MySB/logs/'.

**Comment by CaptainTib** [comment]
Je lance les manips dès maintenant.
Je vous transmet les logs par mail, vous me confirmez la réception? (ce sont les logs avant manipulation)

**Comment by CaptainTib** [comment]
Voici les logs, je fais les manipulations dans la foulée.
﻿

Thibault MAURICE

**Comment by CaptainTib** [comment]
Je ne sais pas si le mail est ok pour vous, .
Une fois l'ensemble des manipulations effectué, je dois redémarrer la machine?

**Comment by toulousain79** [comment]
Mon mail pour les logs : toulousain79-at-gmail.com

 

De : CaptainTib [mailto:notifications@github.com] 
Envoyé : lundi 23 février 2015 16:06
À : toulousain79/MySB
Cc : toulousain79
Objet : Re: [MySB] Problème mise à jour MySB (#6)

 

Voici les logs, je fais les manipulations dans la foulée.
﻿

Thibault MAURICE

**Comment by toulousain79** [comment]
Normalement non, mais vous pouvez faire les manip suivantes en plus, c’est toujours mieux (ca prendra un peu de temps).

 

MySB_UpgradeSystem

MySB_RefreshMe all

MySB_SecurityRules create

 

De : CaptainTib [mailto:notifications@github.com] 
Envoyé : lundi 23 février 2015 16:14
À : toulousain79/MySB
Cc : toulousain79
Objet : Re: [MySB] Problème mise à jour MySB (#6)

 

Je ne sais pas si le mail est ok pour vous, .
Une fois l'ensemble des manipulations effectué, je dois redémarrer la machine?

**Comment by CaptainTib** [comment]
Je refais l'installation au propre, la mise à jour n'a pas été faite correctement.
