### ISSUE TITLE
Ajout d'un user pour l'authentification SSH

### ISSUE THREAD

**Issue by Ayenon** [toulousain79/MySB#61]
Hello

Comme vu via Discord, j'ajoute en ToDo l'idée du user SSH + blocage du root en SSH 

* [x] Ajout d'un utilisateur spécial ou du main user portail MySB pour se connecter en SSH
   * [x] Ajout dans le groupe SUDO
 * [x] Configuration SSH `PermitRootLogin` defaut system, libre modification

**Comment by toulousain79** [comment]
Concernant _PermitRootLogin_, je laisse la valeur par défaut lors d'une installation avec un changement libre.
Idem pour le reste de la config de _sshd_config_, les paramètres liés à MySB seront modifiées sans altérer le reste du fichier.
