### ISSUE TITLE
Répertoire "/var/log/nginx" manquant

### ISSUE THREAD

**Issue by GGTF38** [toulousain79/MySB#64]
Bonjour à tous,

Petite remontée suite à l'installation de deux MySB : 
- l'un samedi dernier
- l'autre ce samedi

Sur les deux installations, il manquait le répertoire /var/log/nginx ce qui empêchait le démarrage du service nginx après reboot.

`mars 02 15:31:49 xxxx.yyyyy.net nginx[4575]: nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or direct`
`mars 02 15:31:49 xxxx.yyyyy.net nginx[4575]: 2019/03/02 15:31:49 [emerg] 4575#4575: open() "/var/log/nginx/access.log" failed (2: No such file or directory)`
`mars 02 15:31:49 xxxx.yyyyy.net nginx[4575]: nginx: configuration file /etc/nginx/nginx.conf test failed`
`mars 02 15:31:49 xxxx.yyyyy.net systemd[1]: nginx.service: Control process exited, code=exited status=1`

Le fait de créer ce répertoire manuellement a corrigé le problème ;)

**Comment by toulousain79** [comment]
Salut,

Peux-tu me de donner plus de détails stp ?
Voir même me fournir les logs d'installation via Discord en message privé _(/opt/MySB/logs/)_.

Car c'est bien la première fois que l'on me remonte cette erreur en 4 ans.
Ce dossier est censé se créer lors de l'installation de Nginx.
Je pense plus un autre problème qui aurait empêché Nginx de s'installer normalement.
Etant donné que la commande **apt-get install** est exécuté à de multiples reprises, l'installation de NginX aurait pu se terminer à un autre moment que lorsqu'elle aurait du.

Peux-tu donc nous rejoindre sur Discord ?

**Comment by GGTF38** [comment]
Salut,

Alors entre temps, j’ai refait complètement mon serveur Kimsufi, j’ai donc supprimé MySB de ce serveur… Je n’ai plus accès aux fichiers LOGs malheureusement.
Il me reste toujours un serveur chez Hetzner avec MySB dessus (et ca tourne du feu de dieu ! Encore merci), je peux te donner les LOGs de ce dernier ci ca t’intéresse car il présentait le même problème. Est-ce que tu veux tous les logs du répertoire ou un en particulier ?

L’OS de base est un Jessie 9.8 Strech 64bits de mémoire.
En RAID0, 32 Go de ram et un Xeon.
Tout s’est bien passé lors de de la dernière installation (j’ai dû refaire plusieurs fois car tu étais en cours de résolution du problème avec Let’s encrypt). A chaque fois, je refaisais une install fresh de l’OS depuis Hetzner, donc tout était supprimé.

Ah si ! un truc qui pourras aider peut-être : je n’ai pas reçu de mail après le redémarrage de l’installation.
J’ai donc conservé un mail d’un installation précédente d’il y a 3 semaines et qui a fonctionnée très bien (sur le même serveur mais je l’avais mis en  RAID6).

En gros on peut simplifier par :

  *   Installation serveur HETZNER en RAID6 il y a 3 semaines --> OK, mail reçu
  *   Installation sur le même serveur HETZNER en RAID0 il y a 2 semaines --> NOK, pas de mail, problème d’accès au répertoire LOG, création du répertoire manuellement --> fonctionnement OK mais toujours pas de mail
  *   Installation sur Kimsufi (supprimé depuis) --> NOK, idem que précédemment

Je n’ai jamais essayé Discord, je peux essayer si tu veux.

Jérôme

De : toulousain79 
Envoyé : jeudi 7 mars 2019 19:36
À : toulousain79/MySB 
Cc : GGTF38 ; Author 
Objet : Re: [toulousain79/MySB] Répertoire "/var/log/nginx" manquant (#64)


Salut,

Peux-tu me de donner plus de détails stp ?
Voir même me fournir les logs d'installation via Discord en message privé (/opt/MySB/logs/).

Car c'est bien la première fois que l'on me remonte cette erreur en 4 ans.
Ce dossier est censé se créé lors de l'installation de Nginx.
Je pense plus un autre problème qui aurait empêché Nginx de s'installé normalement.
Etant donné que la commande apt-get install est exécuté à de multiples reprises, l'installation de NginX aurait pu se terminer à un autre moment que lorsqu'elle aurait du.

Peux-tu donc nous rejoindre sur Discord ?

**Comment by toulousain79** [comment]
Hello,

Merci pour ton retour.
Oui, essaie Discord, c'est très pratique ;-)
[WiKi Support](https://github.com/toulousain79/MySB/wiki/%5BHelp%5D-Support)

Pour les logs, oui je veux bien que tu me les envoies, tous les fichiers contenus dans /optMySB/logs/.
Pour ce qui est du mail de fin d'installation, j'en saurai peut-être plus avec les logs.
Ca peut arriver que le mail ne parte pas lors du choix LOCAL au-lieu de GMAIL ou autre. Dans ce cas, tu peux vérifier les mails en attente sur ton serveur avec la commande `mailq`. A étudier...
[Pour rappel](https://mysb.gitbook.io/doc/installation/lenvoie-de-mails)

**Comment by GGTF38** [comment]
Hello,

Voici les log.
Dans les archives tu trouveras le log de nginx où on peut voir qu’à la fin de l’install il n’a pas réussi a démarrer le service. Après je ne sais pas à quoi cela peut être du.

Jérôme

De : toulousain79 
Envoyé : samedi 9 mars 2019 20:40
À : toulousain79/MySB 
Cc : GGTF38 ; Author
Objet : Re: [toulousain79/MySB] Répertoire "/var/log/nginx" manquant (#64)


Hello,

Merci pour ton retour.
Oui, essaie Discord, c'est très pratique ;-)
WiKi Support<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftoulousain79%2FMySB%2Fwiki%2F%255BHelp%255D-Support&data=02%7C01%7C%7Cc9a2b85318ed4f45bc9008d6a4c70c27%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636877572133287709&sdata=2Z0WMszEVRvg01%2FKtkA3QXSxRaAUmTADhkds6YZGaVg%3D&reserved=0>

Pour les logs, oui je veux bien que tu me les envoies, tous les fichiers contenus dans /optMySB/logs/.
Pour ce qui est du mail de fin d'installation, j'en saurai peut-être plus avec les logs.
Ca peut arriver que le mail ne parte pas lors du choix LOCAL au-lieu de GMAIL ou autre. Dans ce cas, tu peux vérifier les mails en attente sur ton serveur avec la commande mailq. A étudier...
Pour rappel<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmysb.gitbook.io%2Fdoc%2Finstallation%2Flenvoie-de-mails&data=02%7C01%7C%7Cc9a2b85318ed4f45bc9008d6a4c70c27%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636877572133297721&sdata=Uhosji8JccSe%2Bk7iVjTxpK0UuD5hUFalxy%2BjJlG8VQw%3D&reserved=0>

**Comment by toulousain79** [comment]
Cas isolé ?
Pas de réponse de la part de GGTF sur Discord.
Je clôture cette issue

**Comment by pierreandre51** [comment]
Bonjour,
Je déterre ce signalement car j'ai un problème similaire.
J'ai installé le serveur Nginx via SSH par apt install nginx puis apt install php-fpm sur un Raspberry PI4 sous Raspbian buster.
Tout s'est installé normalement et le serveur fonctionne.

MAIS quand je reboote le répertoire des logs "/var/log/nginx" disparait et le service ne démarre pas.
La commande : "sudo service nginx status"
fait apparaitre les erreurs :
janv. 21 18:15:00 raspberrypi-pi4 nginx[486]: nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
janv. 21 18:15:02 raspberrypi-pi4 nginx[486]: 2021/01/21 18:15:00 [emerg] 486#486: open() "/var/log/nginx/access.log" failed (2: No such file or directory)
janv. 21 18:15:02 raspberrypi-pi4 nginx[486]: nginx: configuration file /etc/nginx/nginx.conf test failed
.....
Si je recrée manuellement le répertoire "sudo mkdir /var/log/nginx", tout rentre dans l'ordre jusqu'au prochain arrêt / redémarrage de la machine.

Une idée pour remédier à ce problème ?

Merci

**Comment by toulousain79** [comment]
Bonjour
Je ne fais pas le support pour ce type de cas.
Les RaspBerry ne font pas partis des pré-requis et ne sont pas supportés.
Désolé...
https://mysb.gitbook.io/doc/installation/pre-requis

**Comment by pierreandre51** [comment]
OK, je me suis dépanné en créant le répertoire dans le fichier/etc/rc.dBien que ça ne soit pas satisfaisant pour l'esprit.... Le 23 janv. 2021 12:40, toulousain79 <notifications@github.com> a écrit :

Bonjour

Je ne fais pas le support pour ce type de cas.

Les RaspBerry ne font pas partis des pré-requis et ne sont pas supportés.

Désolé...

https://mysb.gitbook.io/doc/installation/pre-requis

**Comment by pierreandre51** [comment]
J'ai compris pourquoi je perds le répertoire /var/log/nginx :
J'ai mis  les fichiers temporaires et de logs en mémoire vive (tmpfs    /var/log dans le fichier fstab)
C'est donc normal qu'ils disparaissent...
Je laisse comme ça avec la création du répertoire /var/log/nginx dans /etc/rc.loc
et ça fonctionne bien.
