### ISSUE TITLE
Cannot add tarckers

### ISSUE THREAD

**Issue by fravia1** [toulousain79/MySB#7]
Hi,

I tried adding trackers , it keeps giving me a message cannot update database .

Also Is there a way I can remove trackerlist ? I want to allow all trackers.

**Comment by toulousain79** [comment]
Hi,

This function works well.
How much trackers did you add at same time ?
Did you have tried to add your tracker one to one and only with the domain ?
Can you send me your 'ApplyConfig.bsh.log' and 'GetTrackersCert.bsh.log' files ?

For now, there is no option to disable tracker restriction, but maybe I can add this feature in the next version.

**Comment by fravia1** [comment]
Hi,

I think there was some cron update setting that was wrong , now its working fine .

Is there a way I can edit some file and update the trackers ? right now manually putting all the trackers would be a very long process. I can pay you for such a feature.

**Comment by fravia1** [comment]
Also after a while in the rutorrent some error show up
14.03.2015 13:55:51] WebUI started.
[14.03.2015 13:55:53] FILE MANAGER ignited
[14.03.2015 13:57:13] Bad response from server: (0 [error,getchatlist])
[14.03.2015 13:57:13] Bad response from server: (0 [error,getchat])
[14.03.2015 14:10:52] Bad response from server: (0 [error,getratios])
[14.03.2015 14:57:26] Bad response from server: (0 [error,list])

**Comment by toulousain79** [comment]
Hi,
I'm sorry but I do not have time for this project now, and I have not in the weeks to come. I can make some corrections only on the current version and use of MySB_GithubUpdate command. But not the time to do something for the next version.

If you find any bug, please tell me.
For new features, please tell me too.

Bye

**Comment by toulousain79** [comment]
What is the cron bug?

**Comment by fravia1** [comment]
Well , all the trackers in the trackers list were disabled so , the cron job I guess constantly gave a error on rutorrent error : getlist , I enabled all the trackers so far its working fine

**Comment by toulousain79** [comment]
The restriction of trackers is managed by BIND. Configuration files are '/etc/bind/named.conf.local' and '/etc/bind/MySB.zones.blakclists'.
The records in the file 'MySB.zones.blakclists' will be blocked and ruTorrent (and all requests output) necessarily generate an error.
