### ISSUE TITLE
[BUG] Calcul quota ne prend pas en compte l'espace utilisé par l'utilisateur à modifier

### ISSUE THREAD

**Issue by cayenne17** [toulousain79/MySB#72]
Bonjour,
Lors d'une modification quota utilisateur, je ne peux pas définir le quota au dessus de l'espace libre. 
Lors du calcul, l'espace utilisé par l'utilisateur n'est pas pris en compte.
Le maximum que je devrais pouvoir modifier devrait être = **Utiliser par l'utilisateur+espace libre**

![Utilisateurs - Vivaldi_4](https://user-images.githubusercontent.com/47927025/56094153-1ed59380-5ed1-11e9-912a-4c592660b65c.png)

toulousain79 Si tu veux plus de détail, je t'avais signalé le bug sur Discord en MP le 26 février.

Bonne continuation

**Comment by toulousain79** [comment]
Salut
Je relis nos échanges sur Discord.
Il me semblait pourtant que le problème de quota était réglé.
Dans quel contexte tu te retrouves à avoir ce problème ? Car techniquement, un user ne peut pas dépasser sa limite. Et dans ce cas, il est tout à fait possible d'augmenter le quota ou même de le diminuer dans certains cas. Tout dépendra de ton espace de stockage global.
Normalement les correctifs sont appliqués quotidiennement automatiquement via la commande `MySB_GitHubRepoUpdate`.
Je te rejoins sur Discord.

**Comment by toulousain79** [comment]
ok, en fait je ne me suis jamais aperçu du problème car j'ai toujours suffisamment d'espace disque disponible pour faire les calculs
il faut que j'ajoute l'espace déjà occupé par l'utilisateur dans le calcul

Reproduction:
1/ diminuer disque de la VM
2/ fixer le quota en manuel pour un user
3/ combler à 75% l'espace alloué pour ce user
4/ modifier à nouveau l'allocation de l'espace pour ce user

**Comment by toulousain79** [comment]
@cayenne17 
A valider de ton côté, mais du miens ça semble OK.
Il est maintenant possible de saisir n'importe quelle valeur.
Le bug provenait du côté PHP est non du calcul.
