### ISSUE TITLE
Set Up User quota

### ISSUE THREAD

**Issue by fravia1** [toulousain79/MySB#8]
Hi,

Thanks a lot for the script , Is there any way to set up quota space for the user. I tried webmin and so far it doesn't represent the actual disc usage of the user.

Or is there any other way to set it up.

Thanks a lot again

**Comment by fravia1** [comment]
Well , I digged in a bit more and enabled quota on webmin but it seems that each user mounts to its own file system on which disc quota cant be enabled.Any tips on that ?

**Comment by toulousain79** [comment]
Hi, quotas are now included in v3.4. Management remains minimal. The calculation is: (free space - 2GB of security space) / (number of users).
