### ISSUE TITLE
Support docker?

### ISSUE THREAD

**Issue by lhucinequr** [toulousain79/MySB#84]
## Description simple du problème

Pas de support pour docker

## Reproduction du problème

docker-compose up -d

ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

1. '...'
2. '....'
'....'

## Comportement prévisible

Une description claire et concise de ce à quoi tu t'attendais.

## Captures d'écran

Si possible, ajoutes des captures d'écran pour expliquer ton problème.

## Logs

Si possible, ajoutes des logs, ceux se trouvant dans **/opt/MySB/logs**.

## Matériel et environnement

- Hébergeur: _[ex: KimSufi, SoYouStart, ...]_
- Type de serveur: _[ex: VPS, Dédié, ...]_
- Version de MySB: _[ex: v5.3, v5.4 ...]_
- Version du noyau: _(uname -a)_
- Matériel: _(CPU, RAM, HDD, Raid, ...)_

## Contexte supplémentaire

Si nécessaire, ajoutes un autre contexte concernant le problème ici.

**Comment by toulousain79** [comment]
Hello
Pour un `docker-compose up -d`, il faut un fichier **docker-compose.yml** dans le répertoire courant.
Pour ma part, dans MySB, il n'y a, pour l'instant, aucun fichier **docker-compose.yml** disponible.

La version 6.0 est maintenant dispo, mais je n'ai pas encore travailler pour l'intégration d'images Docker.
Je vais m'y mettre.

**Comment by zethis** [comment]
#MEGATROLL #WEWANTDOCKERSUPPORTASAP

**Comment by toulousain79** [comment]
lol, j'avais pas vu
tu payes ?

**Comment by zethis** [comment]
Les binouses et la nuit blanche avec plaisir.
