### ISSUE TITLE
[BUG] installation cassé?

### ISSUE THREAD

**Issue by crzay42** [toulousain79/MySB#85]
## Description simple du problème

depuis ce matin impossibilité  l'installation ne se lance plus après le questionnaire (retour au début  du questionnaire)

## Reproduction du problème

Étapes pour reproduire le problème:

1. '...'
2. '....'
'....'

## Comportement prévisible

Une description claire et concise de ce à quoi tu t'attendais.

## Captures d'écran

Si possible, ajoutes des captures d'écran pour expliquer ton problème.

## Logs

Si possible, ajoutes des logs, ceux se trouvant dans **/opt/MySB/logs**.

pas de logs présent

## Matériel et environnement

- Hébergeur:  Hetzner
- Type de serveur: dédié
- Version de MySB: 6.0 (fait pareil avec la 5.4)
- Version du noyau: _(uname -a)_: 4.9.0-9-amd64

**Comment by crzay42** [comment]
trouvé un log dans /tmp/MySB_install.bsh
juste avant de lancer l'install, j'ai cette erreur : 
No Sockets found in /run/screen/S-root.

**Comment by toulousain79** [comment]
Salut
Tu réponds bien **oui** lors du récapitulatif des questions ?
Car sinon tu retournes au début du questionnaire.

Le message `No Sockets found in /run/screen/S-root.` n'est pas vraiment une erreur. Tu auras ce message aussi à la fin de l'installation.

Je t'invite à venir me rejoindre sur Discord pour en discuter.

**Comment by crzay42** [comment]
en effet,  boulet que je suis j'ai pas répondu oui lors du recap...
