### ISSUE TITLE
Transdroid Crash

### ISSUE THREAD

**Issue by fravia1** [toulousain79/MySB#9]
Hi,

Thanks again for your great script

I was testing transdroid based on the settings on the manager or manually , once the setting is done and you click connect on transdroid , the transdroid application crashes immediately.

**Comment by toulousain79** [comment]
Yes I know, I must find the problem. I think is the new certificate in SHA256. And HTTP I'd not available.

**Comment by toulousain79** [comment]
Done in version 2.1
