### ISSUE TITLE
Plex, synchro des fichiers non fonctionnelle ou partielle

### ISSUE THREAD

**Issue by toulousain79** [toulousain79/MySB#91]
Plusieurs utilisateurs se retrouve avec des bibliothèques non mise à jour, ni manuellement, ni automatiquement.

Upgrade de MySB v6.0 en cause ou dernière version de Plex ?

Je vais installer une version précédente de Plex et tester.

Au niveau de MySB, il n'y a rien, selon moi, qui pourrait interférer avec Plex qui est une application complètement autonome quant au scan et la détection des fichiers, confirmer...

**Comment by toulousain79** [comment]
Problème identifié grâce à la doc de Plex...
https://support.plex.tv/articles/201543057-why-is-some-of-my-content-not-found/

**Comment by toulousain79** [comment]
Vraie fausse route ?
Les droits sur les fichiers sont les mêmes qu'avant.
Après avoir réinstallé Plex en supprimant le fichier `Preferences.xml` juste avant, le scan est à nouveau opérationnel...

A confirmer, j'ai besoin de plus retour d'utilisateurs.

**Comment by Whisper40** [comment]
Salut,malgré que je ne sois pas sur ton installation, il arrive parfois que certaines version de PLEX ne scan plus rien alors que l'app fonctionne.
La solution est pour moi de vider le Cache du Transcoder et de redémarrer PLEX, et après le Scan s relance normalement..

( t'a bien config les scans toutes les X.?)

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by toulousain79** [comment]
Merci pour ton retour.
C'est ce que j'ai fait avant d'essayer une méthode radicale.
Aucun fichier n'était plus détecté, seuls une poignée l'était.
J'ai appliqué les droits sur certains fichiers non détectés avec un `chmod +rx` comme indiqué dans la doc et relancé un scan. Et là ils sont vus directs...
Et à force de manipuler Plex j'ai été contraint de tout désinstaller et nettoyer Plex, puis réinstallation neuve, ainsi qu'un nouvel ajout du serveur à mon compte. Et sans modifier les droits des nouveaux fichiers, là ils sont détectés...
Je me demande si d'un upgrade de Plex à l'autre, un paramètre ou autre n'aurait pas fait bugger la mécanique...

J'attends encore quelques jours et d'autres retour pour voir.

Merci Whisper40

**Comment by toulousain79** [comment]
Tentative  de modification du fichier `Preferences.xml`.
`MySB_GitHubRepoUpdate`

**Comment by toulousain79** [comment]
De mon côté le problème semble être résolu via un `MySB_GitHubRepoUpdate` intégrant un patch corrigeant certainement une erreur avec un mauvais `umask` dans la config rTorrent lors de la création de nouveaux fichiers.
A confirmer par d'autres utilisateurs

**Comment by toulousain79** [comment]
Problème résolu, le patch a corrigé le défaut !
